// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dropper (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        packageBuffer1_V_dout,
        packageBuffer1_V_empty_n,
        packageBuffer1_V_read,
        validFifo_V_dout,
        validFifo_V_empty_n,
        validFifo_V_read,
        dataStreams_V_data_V_din,
        dataStreams_V_data_V_full_n,
        dataStreams_V_data_V_write,
        dataStreams_V_keep_V_din,
        dataStreams_V_keep_V_full_n,
        dataStreams_V_keep_V_write,
        dataStreams_V_last_V_din,
        dataStreams_V_last_V_full_n,
        dataStreams_V_last_V_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [72:0] packageBuffer1_V_dout;
input   packageBuffer1_V_empty_n;
output   packageBuffer1_V_read;
input  [0:0] validFifo_V_dout;
input   validFifo_V_empty_n;
output   validFifo_V_read;
output  [63:0] dataStreams_V_data_V_din;
input   dataStreams_V_data_V_full_n;
output   dataStreams_V_data_V_write;
output  [7:0] dataStreams_V_keep_V_din;
input   dataStreams_V_keep_V_full_n;
output   dataStreams_V_keep_V_write;
output  [0:0] dataStreams_V_last_V_din;
input   dataStreams_V_last_V_full_n;
output   dataStreams_V_last_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg packageBuffer1_V_read;
reg validFifo_V_read;
reg[63:0] dataStreams_V_data_V_din;
reg dataStreams_V_data_V_write;
reg dataStreams_V_keep_V_write;
reg dataStreams_V_last_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] d_isFirstWord;
reg   [0:0] d_drop;
reg    packageBuffer1_V_blk_n;
wire   [0:0] tmp_nbreadreq_fu_54_p3;
wire   [0:0] tmp_18_nbreadreq_fu_81_p3;
reg    validFifo_V_blk_n;
reg    dataStreams_V_data_V_blk_n;
wire   [0:0] tmp_23_read_fu_89_p2;
wire   [0:0] d_drop_load_load_fu_179_p1;
reg    dataStreams_V_keep_V_blk_n;
reg    dataStreams_V_last_V_blk_n;
reg   [0:0] ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10;
reg    ap_predicate_op12_read_state1;
wire    io_acc_block_signal_op17;
reg    ap_predicate_op17_write_state1;
reg    ap_predicate_op23_read_state1;
reg    ap_predicate_op27_read_state1;
wire    io_acc_block_signal_op29;
reg    ap_predicate_op29_write_state1;
reg    ap_block_state1;
reg   [0:0] ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10;
wire   [0:0] grp_fu_162_p3;
wire   [0:0] or_ln347_fu_193_p2;
wire   [0:0] xor_ln347_fu_205_p2;
wire   [0:0] or_ln347_1_fu_199_p2;
wire   [63:0] tmp_data_V_fu_183_p1;
wire   [63:0] tmp_data_V_24_fu_188_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_condition_112;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 d_isFirstWord = 1'd1;
#0 d_drop = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (or_ln347_1_fu_199_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        d_drop <= xor_ln347_fu_205_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (or_ln347_fu_193_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        d_isFirstWord <= packageBuffer1_V_dout[32'd72];
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_23_read_fu_89_p2 == 1'd0) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10 = 1'd1;
    end else if ((((d_drop == 1'd0) & (d_isFirstWord == 1'd0) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((d_isFirstWord == 1'd0) & (d_drop_load_load_fu_179_p1 == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((validFifo_V_dout == 1'd1) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_18_nbreadreq_fu_81_p3 == 1'd0) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10 = 1'd0;
    end else begin
        ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10 = 'bx;
    end
end

always @ (*) begin
    if ((((validFifo_V_dout == 1'd1) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_23_read_fu_89_p2 == 1'd0) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10 = 1'd1;
    end else if ((((d_drop == 1'd0) & (d_isFirstWord == 1'd0) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((d_isFirstWord == 1'd0) & (d_drop_load_load_fu_179_p1 == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_18_nbreadreq_fu_81_p3 == 1'd0) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10 = 1'd0;
    end else begin
        ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10 = 'bx;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (d_drop == 1'd0) & (d_isFirstWord == 1'd0) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (validFifo_V_dout == 1'd1) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        dataStreams_V_data_V_blk_n = dataStreams_V_data_V_full_n;
    end else begin
        dataStreams_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_112)) begin
        if ((ap_predicate_op29_write_state1 == 1'b1)) begin
            dataStreams_V_data_V_din = tmp_data_V_24_fu_188_p1;
        end else if ((ap_predicate_op17_write_state1 == 1'b1)) begin
            dataStreams_V_data_V_din = tmp_data_V_fu_183_p1;
        end else begin
            dataStreams_V_data_V_din = 'bx;
        end
    end else begin
        dataStreams_V_data_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op17_write_state1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op29_write_state1 == 1'b1)))) begin
        dataStreams_V_data_V_write = 1'b1;
    end else begin
        dataStreams_V_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (d_drop == 1'd0) & (d_isFirstWord == 1'd0) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (validFifo_V_dout == 1'd1) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        dataStreams_V_keep_V_blk_n = dataStreams_V_keep_V_full_n;
    end else begin
        dataStreams_V_keep_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op17_write_state1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op29_write_state1 == 1'b1)))) begin
        dataStreams_V_keep_V_write = 1'b1;
    end else begin
        dataStreams_V_keep_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (d_drop == 1'd0) & (d_isFirstWord == 1'd0) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (validFifo_V_dout == 1'd1) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        dataStreams_V_last_V_blk_n = dataStreams_V_last_V_full_n;
    end else begin
        dataStreams_V_last_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op17_write_state1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op29_write_state1 == 1'b1)))) begin
        dataStreams_V_last_V_write = 1'b1;
    end else begin
        dataStreams_V_last_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (d_isFirstWord == 1'd0) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        packageBuffer1_V_blk_n = packageBuffer1_V_empty_n;
    end else begin
        packageBuffer1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op23_read_state1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op12_read_state1 == 1'b1)))) begin
        packageBuffer1_V_read = 1'b1;
    end else begin
        packageBuffer1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        validFifo_V_blk_n = validFifo_V_empty_n;
    end else begin
        validFifo_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1) & (ap_predicate_op27_read_state1 == 1'b1))) begin
        validFifo_V_read = 1'b1;
    end else begin
        validFifo_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1)));
end

always @ (*) begin
    ap_condition_112 = (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((validFifo_V_empty_n == 1'b0) & (ap_predicate_op27_read_state1 == 1'b1)) | ((io_acc_block_signal_op17 == 1'b0) & (ap_predicate_op17_write_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op23_read_state1 == 1'b1)) | ((packageBuffer1_V_empty_n == 1'b0) & (ap_predicate_op12_read_state1 == 1'b1)) | ((io_acc_block_signal_op29 == 1'b0) & (ap_predicate_op29_write_state1 == 1'b1))) & (1'b1 == ap_CS_fsm_state1));
end

always @ (*) begin
    ap_predicate_op12_read_state1 = ((d_isFirstWord == 1'd0) & (tmp_nbreadreq_fu_54_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op17_write_state1 = ((d_drop == 1'd0) & (d_isFirstWord == 1'd0) & (tmp_nbreadreq_fu_54_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op23_read_state1 = ((tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op27_read_state1 = ((tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op29_write_state1 = ((validFifo_V_dout == 1'd1) & (tmp_18_nbreadreq_fu_81_p3 == 1'd1) & (d_isFirstWord == 1'd1) & (tmp_nbreadreq_fu_54_p3 == 1'd1));
end

assign d_drop_load_load_fu_179_p1 = d_drop;

assign dataStreams_V_keep_V_din = {{packageBuffer1_V_dout[71:64]}};

assign dataStreams_V_last_V_din = packageBuffer1_V_dout[32'd72];

assign grp_fu_162_p3 = packageBuffer1_V_dout[32'd72];

assign io_acc_block_signal_op17 = (dataStreams_V_last_V_full_n & dataStreams_V_keep_V_full_n & dataStreams_V_data_V_full_n);

assign io_acc_block_signal_op29 = (dataStreams_V_last_V_full_n & dataStreams_V_keep_V_full_n & dataStreams_V_data_V_full_n);

assign or_ln347_1_fu_199_p2 = (grp_fu_162_p3 | ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10);

assign or_ln347_fu_193_p2 = (grp_fu_162_p3 | ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10);

assign tmp_18_nbreadreq_fu_81_p3 = validFifo_V_empty_n;

assign tmp_23_read_fu_89_p2 = validFifo_V_dout;

assign tmp_data_V_24_fu_188_p1 = packageBuffer1_V_dout[63:0];

assign tmp_data_V_fu_183_p1 = packageBuffer1_V_dout[63:0];

assign tmp_nbreadreq_fu_54_p3 = packageBuffer1_V_empty_n;

assign xor_ln347_fu_205_p2 = (grp_fu_162_p3 ^ 1'd1);

endmodule //dropper
