// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rx_qp_rx_qp,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.323857,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1472,HLS_SYN_LUT=795,HLS_VERSION=2020_2}" *)

module rx_qp (
        ap_clk,
        ap_rst_n,
        rx_req_i_V_TDATA,
        rx_req_i_V_TVALID,
        rx_req_i_V_TREADY,
        rx_req_payload_i_TDATA,
        rx_req_payload_i_TVALID,
        rx_req_payload_i_TREADY,
        rx_req_payload_i_TKEEP,
        rx_req_payload_i_TSTRB,
        rx_req_payload_i_TLAST,
        rx_req_payload_i_TDEST,
        outData_o_TDATA,
        outData_o_TVALID,
        outData_o_TREADY,
        outData_o_TKEEP,
        outData_o_TSTRB,
        outData_o_TLAST,
        outData_o_TDEST,
        axis_tx_resp_ctx_o_V_TDATA,
        axis_tx_resp_ctx_o_V_TVALID,
        axis_tx_resp_ctx_o_V_TREADY,
        qpn_local_i,
        ip_subnet
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [351:0] rx_req_i_V_TDATA;
input   rx_req_i_V_TVALID;
output   rx_req_i_V_TREADY;
input  [511:0] rx_req_payload_i_TDATA;
input   rx_req_payload_i_TVALID;
output   rx_req_payload_i_TREADY;
input  [63:0] rx_req_payload_i_TKEEP;
input  [63:0] rx_req_payload_i_TSTRB;
input  [0:0] rx_req_payload_i_TLAST;
input  [0:0] rx_req_payload_i_TDEST;
output  [511:0] outData_o_TDATA;
output   outData_o_TVALID;
input   outData_o_TREADY;
output  [63:0] outData_o_TKEEP;
output  [63:0] outData_o_TSTRB;
output  [0:0] outData_o_TLAST;
output  [12:0] outData_o_TDEST;
output  [319:0] axis_tx_resp_ctx_o_V_TDATA;
output   axis_tx_resp_ctx_o_V_TVALID;
input   axis_tx_resp_ctx_o_V_TREADY;
input  [23:0] qpn_local_i;
input  [31:0] ip_subnet;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
reg   [1:0] state;
reg   [0:0] data_last_V;
wire   [12:0] msn_V_address0;
reg    msn_V_ce0;
wire   [62:0] msn_V_q0;
wire   [12:0] msn_V_address1;
reg    msn_V_ce1;
reg    msn_V_we1;
reg   [62:0] MSN_Write_V;
reg   [12:0] currentQP_V;
reg   [511:0] data_data_V;
reg   [63:0] data_keep_V;
reg    rx_req_i_V_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
wire   [1:0] state_load_load_fu_438_p1;
wire   [0:0] tmp_nbreadreq_fu_194_p3;
reg    rx_req_payload_i_TDATA_blk_n;
wire   [0:0] d_bth_explicit_ack_V_fu_478_p3;
wire   [0:0] data_last_V_load_load_fu_442_p1;
reg    outData_o_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [1:0] state_load_reg_761;
reg    ap_enable_reg_pp0_iter2;
reg   [1:0] state_load_reg_761_pp0_iter1_reg;
reg    axis_tx_resp_ctx_o_V_TDATA_blk_n;
reg   [0:0] tmp_reg_785;
reg   [0:0] d_bth_explicit_ack_V_reg_794;
reg   [0:0] tmp_reg_785_pp0_iter1_reg;
reg   [0:0] d_bth_explicit_ack_V_reg_794_pp0_iter1_reg;
reg    ap_predicate_op37_read_state1;
reg    ap_predicate_op53_read_state1;
reg    ap_predicate_op63_read_state1;
reg    ap_predicate_op92_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op129_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_predicate_op137_write_state3;
wire    regslice_both_outData_o_V_data_V_U_apdone_blk;
wire    regslice_both_axis_tx_resp_ctx_o_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] data_last_V_load_reg_765;
reg   [12:0] currentQP_V_load_reg_770;
reg   [511:0] data_data_V_load_reg_775;
reg   [63:0] data_keep_V_load_reg_780;
reg   [23:0] trunc_ln145_1_reg_789;
reg   [31:0] tmp_rdma_haddr_reg_798;
reg   [31:0] tmp_rdma_laddr_reg_803;
reg   [23:0] qpn_local_i_read_reg_809;
wire   [7:0] trunc_ln674_1_fu_572_p1;
reg   [7:0] trunc_ln674_1_reg_814;
reg   [7:0] p_Result_s_11_reg_819;
reg   [7:0] p_Result_1_reg_824;
reg   [7:0] p_Result_3_reg_829;
reg   [30:0] trunc_ln_reg_834;
wire   [0:0] tmp_4_fu_621_p3;
reg   [0:0] tmp_4_reg_844;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_state_flag_1_phi_fu_275_p4;
wire   [0:0] ap_phi_reg_pp0_iter1_state_flag_1_reg_272;
wire   [0:0] icmp_ln870_fu_670_p2;
wire   [0:0] icmp_ln878_fu_663_p2;
reg   [1:0] ap_phi_mux_state_new_1_phi_fu_285_p4;
wire   [1:0] ap_phi_reg_pp0_iter1_state_new_1_reg_282;
reg   [63:0] ap_phi_mux_MSN_loc_V_2_phi_fu_296_p4;
wire   [63:0] MSN_loc_V_1_fu_676_p2;
wire   [63:0] ap_phi_reg_pp0_iter1_MSN_loc_V_2_reg_293;
wire   [63:0] zext_ln74_fu_658_p1;
reg   [0:0] ap_phi_mux_state_flag_2_phi_fu_306_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_state_flag_2_reg_302;
reg   [0:0] ap_phi_reg_pp0_iter1_state_flag_2_reg_302;
wire   [0:0] or_ln99_fu_689_p2;
reg   [1:0] ap_phi_mux_state_new_2_phi_fu_317_p4;
wire   [1:0] ap_phi_reg_pp0_iter0_state_new_2_reg_313;
reg   [1:0] ap_phi_reg_pp0_iter1_state_new_2_reg_313;
wire   [1:0] select_ln99_fu_696_p3;
reg   [29:0] ap_phi_mux_ack_syndrome_V_phi_fu_328_p4;
wire   [29:0] ap_phi_reg_pp0_iter0_ack_syndrome_V_reg_324;
reg   [29:0] ap_phi_reg_pp0_iter1_ack_syndrome_V_reg_324;
wire   [29:0] select_ln99_1_fu_705_p3;
reg   [0:0] ap_phi_mux_state_flag_3_phi_fu_340_p16;
wire   [0:0] ap_phi_reg_pp0_iter0_state_flag_3_reg_335;
reg   [0:0] ap_phi_reg_pp0_iter1_state_flag_3_reg_335;
reg   [1:0] ap_phi_mux_state_new_3_phi_fu_371_p16;
wire   [1:0] ap_phi_reg_pp0_iter0_state_new_3_reg_366;
reg   [1:0] ap_phi_reg_pp0_iter1_state_new_3_reg_366;
wire   [63:0] zext_ln534_fu_455_p1;
wire   [63:0] zext_ln534_1_fu_616_p1;
reg   [1:0] ap_sig_allocacmp_state_load;
wire   [62:0] grp_fu_427_p2;
reg   [62:0] ap_sig_allocacmp_MSN_Write_V_load;
reg    ap_block_pp0_stage0_01001;
wire   [62:0] p_Result_12_cast_fu_651_p3;
wire   [7:0] trunc_ln674_fu_506_p1;
wire   [7:0] p_Result_2_fu_510_p4;
wire   [7:0] p_Result_4_fu_520_p4;
wire   [7:0] p_Result_6_fu_530_p4;
wire   [23:0] tmp_1_fu_552_p4;
wire   [31:0] p_Result_s_fu_540_p5;
wire   [31:0] zext_ln208_fu_562_p1;
wire   [31:0] val_V_1_fu_566_p2;
wire   [63:0] p_Result_5_fu_645_p3;
wire   [0:0] icmp_ln886_fu_683_p2;
wire   [189:0] tmp_3_fu_714_p11;
wire   [189:0] or_ln174_fu_732_p2;
wire  signed [190:0] sext_ln174_fu_738_p1;
wire   [191:0] or_ln_fu_742_p3;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_rx_req_i_V_U_apdone_blk;
wire   [351:0] rx_req_i_V_TDATA_int_regslice;
wire    rx_req_i_V_TVALID_int_regslice;
reg    rx_req_i_V_TREADY_int_regslice;
wire    regslice_both_rx_req_i_V_U_ack_in;
wire    regslice_both_rx_req_payload_i_V_data_V_U_apdone_blk;
wire   [511:0] rx_req_payload_i_TDATA_int_regslice;
wire    rx_req_payload_i_TVALID_int_regslice;
reg    rx_req_payload_i_TREADY_int_regslice;
wire    regslice_both_rx_req_payload_i_V_data_V_U_ack_in;
wire    regslice_both_rx_req_payload_i_V_keep_V_U_apdone_blk;
wire   [63:0] rx_req_payload_i_TKEEP_int_regslice;
wire    regslice_both_rx_req_payload_i_V_keep_V_U_vld_out;
wire    regslice_both_rx_req_payload_i_V_keep_V_U_ack_in;
wire    regslice_both_rx_req_payload_i_V_strb_V_U_apdone_blk;
wire   [63:0] rx_req_payload_i_TSTRB_int_regslice;
wire    regslice_both_rx_req_payload_i_V_strb_V_U_vld_out;
wire    regslice_both_rx_req_payload_i_V_strb_V_U_ack_in;
wire    regslice_both_rx_req_payload_i_V_last_V_U_apdone_blk;
wire   [0:0] rx_req_payload_i_TLAST_int_regslice;
wire    regslice_both_rx_req_payload_i_V_last_V_U_vld_out;
wire    regslice_both_rx_req_payload_i_V_last_V_U_ack_in;
wire    regslice_both_rx_req_payload_i_V_dest_V_U_apdone_blk;
wire   [0:0] rx_req_payload_i_TDEST_int_regslice;
wire    regslice_both_rx_req_payload_i_V_dest_V_U_vld_out;
wire    regslice_both_rx_req_payload_i_V_dest_V_U_ack_in;
reg    outData_o_TVALID_int_regslice;
wire    outData_o_TREADY_int_regslice;
wire    regslice_both_outData_o_V_data_V_U_vld_out;
wire    regslice_both_outData_o_V_keep_V_U_apdone_blk;
wire    regslice_both_outData_o_V_keep_V_U_ack_in_dummy;
wire    regslice_both_outData_o_V_keep_V_U_vld_out;
wire    regslice_both_outData_o_V_strb_V_U_apdone_blk;
wire    regslice_both_outData_o_V_strb_V_U_ack_in_dummy;
wire    regslice_both_outData_o_V_strb_V_U_vld_out;
wire    regslice_both_outData_o_V_last_V_U_apdone_blk;
wire    regslice_both_outData_o_V_last_V_U_ack_in_dummy;
wire    regslice_both_outData_o_V_last_V_U_vld_out;
wire    regslice_both_outData_o_V_dest_V_U_apdone_blk;
wire    regslice_both_outData_o_V_dest_V_U_ack_in_dummy;
wire    regslice_both_outData_o_V_dest_V_U_vld_out;
wire   [319:0] axis_tx_resp_ctx_o_V_TDATA_int_regslice;
reg    axis_tx_resp_ctx_o_V_TVALID_int_regslice;
wire    axis_tx_resp_ctx_o_V_TREADY_int_regslice;
wire    regslice_both_axis_tx_resp_ctx_o_V_U_vld_out;
reg    ap_condition_254;
reg    ap_condition_274;
reg    ap_condition_272;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b0;
#0 ap_rst_reg_1 = 1'b0;
#0 ap_rst_n_inv = 1'b0;
#0 state = 2'd0;
#0 data_last_V = 1'd0;
#0 MSN_Write_V = 63'd0;
#0 currentQP_V = 13'd0;
#0 data_data_V = 512'd0;
#0 data_keep_V = 64'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 state_load_reg_761 = 2'd0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 state_load_reg_761_pp0_iter1_reg = 2'd0;
#0 tmp_reg_785 = 1'd0;
#0 d_bth_explicit_ack_V_reg_794 = 1'd0;
#0 tmp_reg_785_pp0_iter1_reg = 1'd0;
#0 d_bth_explicit_ack_V_reg_794_pp0_iter1_reg = 1'd0;
#0 data_last_V_load_reg_765 = 1'd0;
#0 currentQP_V_load_reg_770 = 13'd0;
#0 data_data_V_load_reg_775 = 512'd0;
#0 data_keep_V_load_reg_780 = 64'd0;
#0 trunc_ln145_1_reg_789 = 24'd0;
#0 tmp_rdma_haddr_reg_798 = 32'd0;
#0 tmp_rdma_laddr_reg_803 = 32'd0;
#0 qpn_local_i_read_reg_809 = 24'd0;
#0 trunc_ln674_1_reg_814 = 8'd0;
#0 p_Result_s_11_reg_819 = 8'd0;
#0 p_Result_1_reg_824 = 8'd0;
#0 p_Result_3_reg_829 = 8'd0;
#0 trunc_ln_reg_834 = 31'd0;
#0 tmp_4_reg_844 = 1'd0;
#0 ap_phi_reg_pp0_iter1_state_flag_2_reg_302 = 1'd0;
#0 ap_phi_reg_pp0_iter1_state_new_2_reg_313 = 2'd0;
#0 ap_phi_reg_pp0_iter1_ack_syndrome_V_reg_324 = 30'd0;
#0 ap_phi_reg_pp0_iter1_state_flag_3_reg_335 = 1'd0;
#0 ap_phi_reg_pp0_iter1_state_new_3_reg_366 = 2'd0;
end

rx_qp_msn_V #(
    .DataWidth( 63 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
msn_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(msn_V_address0),
    .ce0(msn_V_ce0),
    .q0(msn_V_q0),
    .address1(msn_V_address1),
    .ce1(msn_V_ce1),
    .we1(msn_V_we1),
    .d1(ap_sig_allocacmp_MSN_Write_V_load)
);

rx_qp_regslice_both #(
    .DataWidth( 352 ))
regslice_both_rx_req_i_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_req_i_V_TDATA),
    .vld_in(rx_req_i_V_TVALID),
    .ack_in(regslice_both_rx_req_i_V_U_ack_in),
    .data_out(rx_req_i_V_TDATA_int_regslice),
    .vld_out(rx_req_i_V_TVALID_int_regslice),
    .ack_out(rx_req_i_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_req_i_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 512 ))
regslice_both_rx_req_payload_i_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_req_payload_i_TDATA),
    .vld_in(rx_req_payload_i_TVALID),
    .ack_in(regslice_both_rx_req_payload_i_V_data_V_U_ack_in),
    .data_out(rx_req_payload_i_TDATA_int_regslice),
    .vld_out(rx_req_payload_i_TVALID_int_regslice),
    .ack_out(rx_req_payload_i_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_req_payload_i_V_data_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 64 ))
regslice_both_rx_req_payload_i_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_req_payload_i_TKEEP),
    .vld_in(rx_req_payload_i_TVALID),
    .ack_in(regslice_both_rx_req_payload_i_V_keep_V_U_ack_in),
    .data_out(rx_req_payload_i_TKEEP_int_regslice),
    .vld_out(regslice_both_rx_req_payload_i_V_keep_V_U_vld_out),
    .ack_out(rx_req_payload_i_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_req_payload_i_V_keep_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 64 ))
regslice_both_rx_req_payload_i_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_req_payload_i_TSTRB),
    .vld_in(rx_req_payload_i_TVALID),
    .ack_in(regslice_both_rx_req_payload_i_V_strb_V_U_ack_in),
    .data_out(rx_req_payload_i_TSTRB_int_regslice),
    .vld_out(regslice_both_rx_req_payload_i_V_strb_V_U_vld_out),
    .ack_out(rx_req_payload_i_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_req_payload_i_V_strb_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 1 ))
regslice_both_rx_req_payload_i_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_req_payload_i_TLAST),
    .vld_in(rx_req_payload_i_TVALID),
    .ack_in(regslice_both_rx_req_payload_i_V_last_V_U_ack_in),
    .data_out(rx_req_payload_i_TLAST_int_regslice),
    .vld_out(regslice_both_rx_req_payload_i_V_last_V_U_vld_out),
    .ack_out(rx_req_payload_i_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_req_payload_i_V_last_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 1 ))
regslice_both_rx_req_payload_i_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_req_payload_i_TDEST),
    .vld_in(rx_req_payload_i_TVALID),
    .ack_in(regslice_both_rx_req_payload_i_V_dest_V_U_ack_in),
    .data_out(rx_req_payload_i_TDEST_int_regslice),
    .vld_out(regslice_both_rx_req_payload_i_V_dest_V_U_vld_out),
    .ack_out(rx_req_payload_i_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_req_payload_i_V_dest_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 512 ))
regslice_both_outData_o_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_data_V_load_reg_775),
    .vld_in(outData_o_TVALID_int_regslice),
    .ack_in(outData_o_TREADY_int_regslice),
    .data_out(outData_o_TDATA),
    .vld_out(regslice_both_outData_o_V_data_V_U_vld_out),
    .ack_out(outData_o_TREADY),
    .apdone_blk(regslice_both_outData_o_V_data_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 64 ))
regslice_both_outData_o_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_keep_V_load_reg_780),
    .vld_in(outData_o_TVALID_int_regslice),
    .ack_in(regslice_both_outData_o_V_keep_V_U_ack_in_dummy),
    .data_out(outData_o_TKEEP),
    .vld_out(regslice_both_outData_o_V_keep_V_U_vld_out),
    .ack_out(outData_o_TREADY),
    .apdone_blk(regslice_both_outData_o_V_keep_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 64 ))
regslice_both_outData_o_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(64'd0),
    .vld_in(outData_o_TVALID_int_regslice),
    .ack_in(regslice_both_outData_o_V_strb_V_U_ack_in_dummy),
    .data_out(outData_o_TSTRB),
    .vld_out(regslice_both_outData_o_V_strb_V_U_vld_out),
    .ack_out(outData_o_TREADY),
    .apdone_blk(regslice_both_outData_o_V_strb_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 1 ))
regslice_both_outData_o_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_last_V_load_reg_765),
    .vld_in(outData_o_TVALID_int_regslice),
    .ack_in(regslice_both_outData_o_V_last_V_U_ack_in_dummy),
    .data_out(outData_o_TLAST),
    .vld_out(regslice_both_outData_o_V_last_V_U_vld_out),
    .ack_out(outData_o_TREADY),
    .apdone_blk(regslice_both_outData_o_V_last_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 13 ))
regslice_both_outData_o_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(currentQP_V_load_reg_770),
    .vld_in(outData_o_TVALID_int_regslice),
    .ack_in(regslice_both_outData_o_V_dest_V_U_ack_in_dummy),
    .data_out(outData_o_TDEST),
    .vld_out(regslice_both_outData_o_V_dest_V_U_vld_out),
    .ack_out(outData_o_TREADY),
    .apdone_blk(regslice_both_outData_o_V_dest_V_U_apdone_blk)
);

rx_qp_regslice_both #(
    .DataWidth( 320 ))
regslice_both_axis_tx_resp_ctx_o_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axis_tx_resp_ctx_o_V_TDATA_int_regslice),
    .vld_in(axis_tx_resp_ctx_o_V_TVALID_int_regslice),
    .ack_in(axis_tx_resp_ctx_o_V_TREADY_int_regslice),
    .data_out(axis_tx_resp_ctx_o_V_TDATA),
    .vld_out(regslice_both_axis_tx_resp_ctx_o_V_U_vld_out),
    .ack_out(axis_tx_resp_ctx_o_V_TREADY),
    .apdone_blk(regslice_both_axis_tx_resp_ctx_o_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        MSN_Write_V <= 63'd0;
    end else begin
        if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_4_reg_844 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln870_fu_670_p2 == 1'd1) & (tmp_4_reg_844 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0)))) begin
            MSN_Write_V <= grp_fu_427_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_phi_reg_pp0_iter1_ack_syndrome_V_reg_324 <= 30'd0;
    end else begin
        if ((1'b1 == ap_condition_272)) begin
            if ((1'b1 == ap_condition_274)) begin
                ap_phi_reg_pp0_iter1_ack_syndrome_V_reg_324 <= 30'd0;
            end else if ((1'b1 == 1'b1)) begin
                ap_phi_reg_pp0_iter1_ack_syndrome_V_reg_324 <= ap_phi_reg_pp0_iter0_ack_syndrome_V_reg_324;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_phi_reg_pp0_iter1_state_flag_2_reg_302 <= 1'd0;
    end else begin
        if ((1'b1 == ap_condition_272)) begin
            if ((1'b1 == ap_condition_274)) begin
                ap_phi_reg_pp0_iter1_state_flag_2_reg_302 <= 1'd1;
            end else if ((1'b1 == 1'b1)) begin
                ap_phi_reg_pp0_iter1_state_flag_2_reg_302 <= ap_phi_reg_pp0_iter0_state_flag_2_reg_302;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_phi_reg_pp0_iter1_state_flag_3_reg_335 <= 1'd0;
    end else begin
        if ((((data_last_V_load_load_fu_442_p1 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((data_last_V_load_load_fu_442_p1 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_phi_reg_pp0_iter1_state_flag_3_reg_335 <= 1'd1;
        end else if ((((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_nbreadreq_fu_194_p3 == 1'd0) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((d_bth_explicit_ack_V_fu_478_p3 == 1'd0) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((state_load_load_fu_438_p1 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_phi_reg_pp0_iter1_state_flag_3_reg_335 <= 1'd0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_phi_reg_pp0_iter1_state_flag_3_reg_335 <= ap_phi_reg_pp0_iter0_state_flag_3_reg_335;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_phi_reg_pp0_iter1_state_new_2_reg_313 <= 2'd0;
    end else begin
        if ((1'b1 == ap_condition_272)) begin
            if ((1'b1 == ap_condition_274)) begin
                ap_phi_reg_pp0_iter1_state_new_2_reg_313 <= 2'd1;
            end else if ((1'b1 == 1'b1)) begin
                ap_phi_reg_pp0_iter1_state_new_2_reg_313 <= ap_phi_reg_pp0_iter0_state_new_2_reg_313;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_phi_reg_pp0_iter1_state_new_3_reg_366 <= 2'd0;
    end else begin
        if ((((data_last_V_load_load_fu_442_p1 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((data_last_V_load_load_fu_442_p1 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_phi_reg_pp0_iter1_state_new_3_reg_366 <= 2'd0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_phi_reg_pp0_iter1_state_new_3_reg_366 <= ap_phi_reg_pp0_iter0_state_new_3_reg_366;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_rst_n_inv <= 1'b0;
    end else begin
        ap_rst_n_inv <= ap_rst_reg_1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_rst_reg_1 <= 1'b0;
    end else begin
        ap_rst_reg_1 <= ap_rst_reg_2;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_rst_reg_2 <= 1'b0;
    end else begin
        ap_rst_reg_2 <= ~ap_rst_n;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        currentQP_V <= 13'd0;
    end else begin
        if (((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            currentQP_V <= {{rx_req_i_V_TDATA_int_regslice[108:96]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        currentQP_V_load_reg_770 <= 13'd0;
    end else begin
        if (((ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            currentQP_V_load_reg_770 <= currentQP_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        d_bth_explicit_ack_V_reg_794 <= 1'd0;
    end else begin
        if (((tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            d_bth_explicit_ack_V_reg_794 <= rx_req_i_V_TDATA_int_regslice[32'd128];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        d_bth_explicit_ack_V_reg_794_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            d_bth_explicit_ack_V_reg_794_pp0_iter1_reg <= d_bth_explicit_ack_V_reg_794;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_data_V <= 512'd0;
    end else begin
        if ((((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            data_data_V <= rx_req_payload_i_TDATA_int_regslice;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_data_V_load_reg_775 <= 512'd0;
    end else begin
        if (((ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            data_data_V_load_reg_775 <= data_data_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_keep_V <= 64'd0;
    end else begin
        if ((((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            data_keep_V <= rx_req_payload_i_TKEEP_int_regslice;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_keep_V_load_reg_780 <= 64'd0;
    end else begin
        if (((ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            data_keep_V_load_reg_780 <= data_keep_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_last_V <= 1'd0;
    end else begin
        if ((((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            data_last_V <= rx_req_payload_i_TLAST_int_regslice;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_last_V_load_reg_765 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            data_last_V_load_reg_765 <= data_last_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        p_Result_1_reg_824 <= 8'd0;
    end else begin
        if (((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_Result_1_reg_824 <= {{val_V_1_fu_566_p2[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        p_Result_3_reg_829 <= 8'd0;
    end else begin
        if (((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_Result_3_reg_829 <= {{val_V_1_fu_566_p2[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        p_Result_s_11_reg_819 <= 8'd0;
    end else begin
        if (((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_Result_s_11_reg_819 <= {{val_V_1_fu_566_p2[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        qpn_local_i_read_reg_809 <= 24'd0;
    end else begin
        if (((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            qpn_local_i_read_reg_809 <= qpn_local_i;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        state <= 2'd0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_state_flag_3_phi_fu_340_p16 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            state <= ap_phi_mux_state_new_3_phi_fu_371_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        state_load_reg_761 <= 2'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            state_load_reg_761 <= ap_sig_allocacmp_state_load;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        state_load_reg_761_pp0_iter1_reg <= 2'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            state_load_reg_761_pp0_iter1_reg <= state_load_reg_761;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        tmp_4_reg_844 <= 1'd0;
    end else begin
        if (((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_4_reg_844 <= rx_req_i_V_TDATA_int_regslice[32'd191];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        tmp_rdma_haddr_reg_798 <= 32'd0;
    end else begin
        if (((tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_rdma_haddr_reg_798 <= {{rx_req_i_V_TDATA_int_regslice[191:160]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        tmp_rdma_laddr_reg_803 <= 32'd0;
    end else begin
        if (((tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_rdma_laddr_reg_803 <= {{rx_req_i_V_TDATA_int_regslice[223:192]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        tmp_reg_785 <= 1'd0;
    end else begin
        if (((ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_reg_785 <= tmp_nbreadreq_fu_194_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        tmp_reg_785_pp0_iter1_reg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tmp_reg_785_pp0_iter1_reg <= tmp_reg_785;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        trunc_ln145_1_reg_789 <= 24'd0;
    end else begin
        if (((tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            trunc_ln145_1_reg_789 <= {{rx_req_i_V_TDATA_int_regslice[87:64]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        trunc_ln674_1_reg_814 <= 8'd0;
    end else begin
        if (((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            trunc_ln674_1_reg_814 <= trunc_ln674_1_fu_572_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        trunc_ln_reg_834 <= 31'd0;
    end else begin
        if (((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            trunc_ln_reg_834 <= {{rx_req_i_V_TDATA_int_regslice[190:160]}};
        end
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_254)) begin
        if ((icmp_ln870_fu_670_p2 == 1'd0)) begin
            ap_phi_mux_MSN_loc_V_2_phi_fu_296_p4 = zext_ln74_fu_658_p1;
        end else if ((icmp_ln870_fu_670_p2 == 1'd1)) begin
            ap_phi_mux_MSN_loc_V_2_phi_fu_296_p4 = MSN_loc_V_1_fu_676_p2;
        end else begin
            ap_phi_mux_MSN_loc_V_2_phi_fu_296_p4 = ap_phi_reg_pp0_iter1_MSN_loc_V_2_reg_293;
        end
    end else begin
        ap_phi_mux_MSN_loc_V_2_phi_fu_296_p4 = ap_phi_reg_pp0_iter1_MSN_loc_V_2_reg_293;
    end
end

always @ (*) begin
    if (((tmp_4_reg_844 == 1'd0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0))) begin
        ap_phi_mux_ack_syndrome_V_phi_fu_328_p4 = select_ln99_1_fu_705_p3;
    end else begin
        ap_phi_mux_ack_syndrome_V_phi_fu_328_p4 = ap_phi_reg_pp0_iter1_ack_syndrome_V_reg_324;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_254)) begin
        if ((icmp_ln870_fu_670_p2 == 1'd0)) begin
            ap_phi_mux_state_flag_1_phi_fu_275_p4 = icmp_ln878_fu_663_p2;
        end else if ((icmp_ln870_fu_670_p2 == 1'd1)) begin
            ap_phi_mux_state_flag_1_phi_fu_275_p4 = 1'd1;
        end else begin
            ap_phi_mux_state_flag_1_phi_fu_275_p4 = ap_phi_reg_pp0_iter1_state_flag_1_reg_272;
        end
    end else begin
        ap_phi_mux_state_flag_1_phi_fu_275_p4 = ap_phi_reg_pp0_iter1_state_flag_1_reg_272;
    end
end

always @ (*) begin
    if (((tmp_4_reg_844 == 1'd0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0))) begin
        ap_phi_mux_state_flag_2_phi_fu_306_p4 = or_ln99_fu_689_p2;
    end else begin
        ap_phi_mux_state_flag_2_phi_fu_306_p4 = ap_phi_reg_pp0_iter1_state_flag_2_reg_302;
    end
end

always @ (*) begin
    if (((d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0))) begin
        ap_phi_mux_state_flag_3_phi_fu_340_p16 = ap_phi_mux_state_flag_2_phi_fu_306_p4;
    end else begin
        ap_phi_mux_state_flag_3_phi_fu_340_p16 = ap_phi_reg_pp0_iter1_state_flag_3_reg_335;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_254)) begin
        if ((icmp_ln870_fu_670_p2 == 1'd0)) begin
            ap_phi_mux_state_new_1_phi_fu_285_p4 = 2'd2;
        end else if ((icmp_ln870_fu_670_p2 == 1'd1)) begin
            ap_phi_mux_state_new_1_phi_fu_285_p4 = 2'd1;
        end else begin
            ap_phi_mux_state_new_1_phi_fu_285_p4 = ap_phi_reg_pp0_iter1_state_new_1_reg_282;
        end
    end else begin
        ap_phi_mux_state_new_1_phi_fu_285_p4 = ap_phi_reg_pp0_iter1_state_new_1_reg_282;
    end
end

always @ (*) begin
    if (((tmp_4_reg_844 == 1'd0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0))) begin
        ap_phi_mux_state_new_2_phi_fu_317_p4 = select_ln99_fu_696_p3;
    end else begin
        ap_phi_mux_state_new_2_phi_fu_317_p4 = ap_phi_reg_pp0_iter1_state_new_2_reg_313;
    end
end

always @ (*) begin
    if (((d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0))) begin
        ap_phi_mux_state_new_3_phi_fu_371_p16 = ap_phi_mux_state_new_2_phi_fu_317_p4;
    end else begin
        ap_phi_mux_state_new_3_phi_fu_371_p16 = ap_phi_reg_pp0_iter1_state_new_3_reg_366;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (tmp_4_reg_844 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln870_fu_670_p2 == 1'd1) & (tmp_4_reg_844 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0)))) begin
        ap_sig_allocacmp_MSN_Write_V_load = grp_fu_427_p2;
    end else begin
        ap_sig_allocacmp_MSN_Write_V_load = MSN_Write_V;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_state_flag_3_phi_fu_340_p16 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_state_load = ap_phi_mux_state_new_3_phi_fu_371_p16;
    end else begin
        ap_sig_allocacmp_state_load = state;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (d_bth_explicit_ack_V_reg_794_pp0_iter1_reg == 1'd1) & (tmp_reg_785_pp0_iter1_reg == 1'd1) & (state_load_reg_761_pp0_iter1_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0)))) begin
        axis_tx_resp_ctx_o_V_TDATA_blk_n = axis_tx_resp_ctx_o_V_TREADY_int_regslice;
    end else begin
        axis_tx_resp_ctx_o_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op129_write_state2 == 1'b1))) begin
        axis_tx_resp_ctx_o_V_TVALID_int_regslice = 1'b1;
    end else begin
        axis_tx_resp_ctx_o_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        msn_V_ce0 = 1'b1;
    end else begin
        msn_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        msn_V_ce1 = 1'b1;
    end else begin
        msn_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        msn_V_we1 = 1'b1;
    end else begin
        msn_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (state_load_reg_761_pp0_iter1_reg == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (state_load_reg_761 == 2'd1)))) begin
        outData_o_TDATA_blk_n = outData_o_TREADY_int_regslice;
    end else begin
        outData_o_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (state_load_reg_761 == 2'd1))) begin
        outData_o_TVALID_int_regslice = 1'b1;
    end else begin
        outData_o_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_req_i_V_TDATA_blk_n = rx_req_i_V_TVALID_int_regslice;
    end else begin
        rx_req_i_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op63_read_state1 == 1'b1))) begin
        rx_req_i_V_TREADY_int_regslice = 1'b1;
    end else begin
        rx_req_i_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd2) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        rx_req_payload_i_TDATA_blk_n = rx_req_payload_i_TVALID_int_regslice;
    end else begin
        rx_req_payload_i_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op92_read_state1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op53_read_state1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op37_read_state1 == 1'b1)))) begin
        rx_req_payload_i_TREADY_int_regslice = 1'b1;
    end else begin
        rx_req_payload_i_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign MSN_loc_V_1_fu_676_p2 = (p_Result_5_fu_645_p3 + 64'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == 1'b1) & (((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op92_read_state1 == 1'b1)) | ((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op53_read_state1 == 1'b1)) | ((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op37_read_state1 == 1'b1)) | ((rx_req_i_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op63_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_axis_tx_resp_ctx_o_V_U_apdone_blk == 1'b1) | (regslice_both_outData_o_V_data_V_U_apdone_blk == 1'b1) | ((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op137_write_state3 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761_pp0_iter1_reg == 2'd1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op129_write_state2 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761 == 2'd1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == 1'b1) & (((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op92_read_state1 == 1'b1)) | ((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op53_read_state1 == 1'b1)) | ((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op37_read_state1 == 1'b1)) | ((rx_req_i_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op63_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | (regslice_both_axis_tx_resp_ctx_o_V_U_apdone_blk == 1'b1) | (regslice_both_outData_o_V_data_V_U_apdone_blk == 1'b1) | ((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op137_write_state3 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761_pp0_iter1_reg == 2'd1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op129_write_state2 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761 == 2'd1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == 1'b1) & (((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op92_read_state1 == 1'b1)) | ((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op53_read_state1 == 1'b1)) | ((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op37_read_state1 == 1'b1)) | ((rx_req_i_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op63_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | (regslice_both_axis_tx_resp_ctx_o_V_U_apdone_blk == 1'b1) | (regslice_both_outData_o_V_data_V_U_apdone_blk == 1'b1) | ((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op137_write_state3 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761_pp0_iter1_reg == 2'd1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op129_write_state2 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761 == 2'd1)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op92_read_state1 == 1'b1)) | ((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op53_read_state1 == 1'b1)) | ((rx_req_payload_i_TVALID_int_regslice == 1'b0) & (ap_predicate_op37_read_state1 == 1'b1)) | ((rx_req_i_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op63_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_io = (((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op129_write_state2 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761 == 2'd1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op129_write_state2 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761 == 2'd1)));
end

always @ (*) begin
    ap_block_state3_io = (((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op137_write_state3 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761_pp0_iter1_reg == 2'd1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_axis_tx_resp_ctx_o_V_U_apdone_blk == 1'b1) | (regslice_both_outData_o_V_data_V_U_apdone_blk == 1'b1) | ((axis_tx_resp_ctx_o_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op137_write_state3 == 1'b1)) | ((outData_o_TREADY_int_regslice == 1'b0) & (state_load_reg_761_pp0_iter1_reg == 2'd1)));
end

always @ (*) begin
    ap_condition_254 = ((tmp_4_reg_844 == 1'd0) & (d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0));
end

always @ (*) begin
    ap_condition_272 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_274 = ((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0) & (tmp_4_fu_621_p3 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_ack_syndrome_V_reg_324 = 'bx;

assign ap_phi_reg_pp0_iter0_state_flag_2_reg_302 = 'bx;

assign ap_phi_reg_pp0_iter0_state_flag_3_reg_335 = 'bx;

assign ap_phi_reg_pp0_iter0_state_new_2_reg_313 = 'bx;

assign ap_phi_reg_pp0_iter0_state_new_3_reg_366 = 'bx;

assign ap_phi_reg_pp0_iter1_MSN_loc_V_2_reg_293 = 'bx;

assign ap_phi_reg_pp0_iter1_state_flag_1_reg_272 = 'bx;

assign ap_phi_reg_pp0_iter1_state_new_1_reg_282 = 'bx;

always @ (*) begin
    ap_predicate_op129_write_state2 = ((d_bth_explicit_ack_V_reg_794 == 1'd1) & (tmp_reg_785 == 1'd1) & (state_load_reg_761 == 2'd0));
end

always @ (*) begin
    ap_predicate_op137_write_state3 = ((d_bth_explicit_ack_V_reg_794_pp0_iter1_reg == 1'd1) & (tmp_reg_785_pp0_iter1_reg == 1'd1) & (state_load_reg_761_pp0_iter1_reg == 2'd0));
end

always @ (*) begin
    ap_predicate_op37_read_state1 = ((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd2));
end

always @ (*) begin
    ap_predicate_op53_read_state1 = ((data_last_V == 1'd0) & (ap_sig_allocacmp_state_load == 2'd1));
end

always @ (*) begin
    ap_predicate_op63_read_state1 = ((tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0));
end

always @ (*) begin
    ap_predicate_op92_read_state1 = ((d_bth_explicit_ack_V_fu_478_p3 == 1'd1) & (tmp_nbreadreq_fu_194_p3 == 1'd1) & (ap_sig_allocacmp_state_load == 2'd0));
end

assign axis_tx_resp_ctx_o_V_TDATA_int_regslice = or_ln_fu_742_p3;

assign axis_tx_resp_ctx_o_V_TVALID = regslice_both_axis_tx_resp_ctx_o_V_U_vld_out;

assign d_bth_explicit_ack_V_fu_478_p3 = rx_req_i_V_TDATA_int_regslice[32'd128];

assign data_last_V_load_load_fu_442_p1 = data_last_V;

assign grp_fu_427_p2 = (p_Result_12_cast_fu_651_p3 + 63'd1);

assign icmp_ln870_fu_670_p2 = ((p_Result_5_fu_645_p3 == zext_ln74_fu_658_p1) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_663_p2 = ((p_Result_5_fu_645_p3 < zext_ln74_fu_658_p1) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_683_p2 = ((p_Result_5_fu_645_p3 > ap_phi_mux_MSN_loc_V_2_phi_fu_296_p4) ? 1'b1 : 1'b0);

assign msn_V_address0 = zext_ln534_1_fu_616_p1;

assign msn_V_address1 = zext_ln534_fu_455_p1;

assign or_ln174_fu_732_p2 = (tmp_3_fu_714_p11 | 190'd16725558898897967376703527637934967099490304);

assign or_ln99_fu_689_p2 = (icmp_ln886_fu_683_p2 | ap_phi_mux_state_flag_1_phi_fu_275_p4);

assign or_ln_fu_742_p3 = {{1'd0}, {sext_ln174_fu_738_p1}};

assign outData_o_TVALID = regslice_both_outData_o_V_data_V_U_vld_out;

assign p_Result_12_cast_fu_651_p3 = {{trunc_ln_reg_834}, {tmp_rdma_laddr_reg_803}};

assign p_Result_2_fu_510_p4 = {{ip_subnet[15:8]}};

assign p_Result_4_fu_520_p4 = {{ip_subnet[23:16]}};

assign p_Result_5_fu_645_p3 = {{tmp_rdma_haddr_reg_798}, {tmp_rdma_laddr_reg_803}};

assign p_Result_6_fu_530_p4 = {{ip_subnet[31:24]}};

assign p_Result_s_fu_540_p5 = {{{{trunc_ln674_fu_506_p1}, {p_Result_2_fu_510_p4}}, {p_Result_4_fu_520_p4}}, {p_Result_6_fu_530_p4}};

assign rx_req_i_V_TREADY = regslice_both_rx_req_i_V_U_ack_in;

assign rx_req_payload_i_TREADY = regslice_both_rx_req_payload_i_V_data_V_U_ack_in;

assign select_ln99_1_fu_705_p3 = ((icmp_ln886_fu_683_p2[0:0] == 1'b1) ? 30'd536870912 : 30'd0);

assign select_ln99_fu_696_p3 = ((icmp_ln886_fu_683_p2[0:0] == 1'b1) ? 2'd2 : ap_phi_mux_state_new_1_phi_fu_285_p4);

assign sext_ln174_fu_738_p1 = $signed(or_ln174_fu_732_p2);

assign state_load_load_fu_438_p1 = ap_sig_allocacmp_state_load;

assign tmp_1_fu_552_p4 = {{rx_req_i_V_TDATA_int_regslice[119:96]}};

assign tmp_3_fu_714_p11 = {{{{{{{{{{ap_phi_mux_ack_syndrome_V_phi_fu_328_p4}, {32'd0}}, {trunc_ln674_1_reg_814}}, {p_Result_s_11_reg_819}}, {p_Result_1_reg_824}}, {p_Result_3_reg_829}}, {40'd0}}, {trunc_ln145_1_reg_789}}, {8'd0}}, {qpn_local_i_read_reg_809}};

assign tmp_4_fu_621_p3 = rx_req_i_V_TDATA_int_regslice[32'd191];

assign tmp_nbreadreq_fu_194_p3 = rx_req_i_V_TVALID_int_regslice;

assign trunc_ln674_1_fu_572_p1 = val_V_1_fu_566_p2[7:0];

assign trunc_ln674_fu_506_p1 = ip_subnet[7:0];

assign val_V_1_fu_566_p2 = (p_Result_s_fu_540_p5 + zext_ln208_fu_562_p1);

assign zext_ln208_fu_562_p1 = tmp_1_fu_552_p4;

assign zext_ln534_1_fu_616_p1 = tmp_1_fu_552_p4;

assign zext_ln534_fu_455_p1 = currentQP_V;

assign zext_ln74_fu_658_p1 = msn_V_q0;

endmodule //rx_qp
