// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tx_rdma_hdr_put_hdr (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ecn_for_ack_dout,
        ecn_for_ack_empty_n,
        ecn_for_ack_read,
        tx_to_hdr_gen_dout,
        tx_to_hdr_gen_empty_n,
        tx_to_hdr_gen_read,
        axis_frame_ctx_to_hdr_gen_dout,
        axis_frame_ctx_to_hdr_gen_empty_n,
        axis_frame_ctx_to_hdr_gen_read,
        payload_remainder_din,
        payload_remainder_full_n,
        payload_remainder_write,
        tx_to_crc_and_remainder_din,
        tx_to_crc_and_remainder_full_n,
        tx_to_crc_and_remainder_write,
        packet_len,
        packet_len_ap_vld,
        rdma_udp_port_dst,
        my_ip
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_const_lv16_0 = 16'd0;



input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] ecn_for_ack_dout;
input   ecn_for_ack_empty_n;
output   ecn_for_ack_read;
input  [1023:0] tx_to_hdr_gen_dout;
input   tx_to_hdr_gen_empty_n;
output   tx_to_hdr_gen_read;
input  [280:0] axis_frame_ctx_to_hdr_gen_dout;
input   axis_frame_ctx_to_hdr_gen_empty_n;
output   axis_frame_ctx_to_hdr_gen_read;
output  [1:0] payload_remainder_din;
input   payload_remainder_full_n;
output   payload_remainder_write;
output  [1023:0] tx_to_crc_and_remainder_din;
input   tx_to_crc_and_remainder_full_n;
output   tx_to_crc_and_remainder_write;
output  [31:0] packet_len;
output   packet_len_ap_vld;
input  [15:0] rdma_udp_port_dst;
input  [31:0] my_ip;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ecn_for_ack_read;
reg tx_to_hdr_gen_read;
reg axis_frame_ctx_to_hdr_gen_read;
reg payload_remainder_write;
reg tx_to_crc_and_remainder_write;
reg[31:0] packet_len;
reg packet_len_ap_vld;

reg    ap_done_reg;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire   [0:0] tmp_i_i_nbreadreq_fu_332_p3;
wire   [0:0] tmp_1_i_i_nbreadreq_fu_340_p3;
reg    ap_predicate_op42_read_state1;
reg    ap_predicate_op46_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] tmp_i_i_reg_2667;
reg   [0:0] ls_firstWord_1_load_reg_2671;
reg   [0:0] tmp_1_i_i_reg_2675;
reg    ap_predicate_op203_write_state2;
reg    ap_predicate_op209_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] ls_firstWord_1;
reg   [15:0] id;
reg    ecn_for_ack_blk_n;
reg    tx_to_hdr_gen_blk_n;
reg    axis_frame_ctx_to_hdr_gen_blk_n;
reg    payload_remainder_blk_n;
reg    tx_to_crc_and_remainder_blk_n;
wire   [511:0] tmp_data_V_1_fu_431_p1;
wire   [1:0] payload_rem_V_1_fu_502_p2;
reg   [1:0] payload_rem_V_1_reg_2684;
wire   [15:0] ip_len_V_fu_2548_p2;
reg   [15:0] ip_len_V_reg_2689;
wire   [511:0] p_Result_17_fu_2616_p5;
reg   [64:0] tmp_reg_2699;
reg   [0:0] ap_phi_mux_ls_firstWord_3_flag_0_i_i_phi_fu_384_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_ls_firstWord_3_flag_0_i_i_reg_381;
reg   [0:0] ap_phi_mux_ls_firstWord_3_flag_1_i_i_phi_fu_395_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_ls_firstWord_3_flag_1_i_i_reg_392;
wire   [0:0] or_ln454_fu_2638_p2;
reg   [0:0] ap_phi_mux_ls_firstWord_3_new_1_i_i_phi_fu_408_p6;
wire   [0:0] tmp_last_V_fu_435_p3;
wire   [0:0] ap_phi_reg_pp0_iter0_ls_firstWord_3_new_1_i_i_reg_405;
wire   [511:0] ap_phi_reg_pp0_iter0_din_data_V_reg_418;
reg   [511:0] ap_phi_reg_pp0_iter1_din_data_V_reg_418;
wire   [15:0] add_ln691_4_fu_2572_p2;
wire   [31:0] zext_ln208_fu_2651_p1;
reg   [31:0] packet_len_preg;
wire   [1:0] p_Result_i_i_fu_492_p4;
wire   [7:0] p_Result_2_i_i_fu_542_p4;
wire   [7:0] p_Result_3_i_i_fu_552_p4;
wire   [7:0] p_Result_4_i_i_fu_562_p4;
wire   [0:0] frame_ctx_explicit_ack_1_fu_464_p3;
wire   [7:0] trunc_ln674_fu_518_p1;
wire   [7:0] p_Result_i_i_52_fu_522_p4;
wire   [7:0] p_Result_1_i_i_fu_532_p4;
wire   [4:0] trunc_ln_fu_508_p4;
wire   [95:0] tmp_2_i_i_fu_572_p13;
wire   [7:0] tmp_opcode_V_fu_454_p4;
wire   [7:0] p_Result_19_i_i_fu_736_p4;
wire   [7:0] p_Result_20_i_i_fu_746_p4;
wire   [7:0] p_Result_21_i_i_fu_756_p4;
wire   [7:0] p_Result_22_i_i_fu_766_p4;
wire   [7:0] p_Result_15_i_i_fu_696_p4;
wire   [7:0] p_Result_16_i_i_fu_706_p4;
wire   [7:0] p_Result_17_i_i_fu_716_p4;
wire   [7:0] p_Result_18_i_i_fu_726_p4;
wire   [7:0] p_Result_11_i_i_fu_656_p4;
wire   [7:0] p_Result_12_i_i_fu_666_p4;
wire   [7:0] p_Result_13_i_i_fu_676_p4;
wire   [7:0] p_Result_14_i_i_fu_686_p4;
wire   [7:0] p_Result_6_i_i_fu_616_p4;
wire   [7:0] p_Result_7_i_i_fu_626_p4;
wire   [7:0] p_Result_8_i_i_fu_636_p4;
wire   [7:0] p_Result_10_i_i_fu_646_p4;
wire   [511:0] p_Result_s_fu_600_p5;
wire   [127:0] tmp_3_i_i_fu_776_p17;
wire   [0:0] icmp_ln41_1_fu_830_p2;
wire   [0:0] icmp_ln41_2_fu_836_p2;
wire   [0:0] or_ln41_fu_842_p2;
wire   [0:0] icmp_ln41_fu_824_p2;
wire   [0:0] or_ln41_1_fu_848_p2;
wire   [511:0] p_Result_1_fu_812_p5;
wire   [31:0] tmp_immdt_V_fu_482_p4;
wire   [31:0] select_ln155_fu_862_p3;
wire   [31:0] select_ln215_fu_876_p3;
wire   [9:0] trunc_ln414_fu_894_p1;
wire   [0:0] icmp_ln414_fu_888_p2;
wire   [9:0] trunc_ln414_1_fu_898_p1;
wire   [9:0] xor_ln414_fu_902_p2;
wire   [9:0] select_ln414_fu_908_p3;
wire   [9:0] select_ln414_2_fu_924_p3;
wire   [9:0] select_ln414_1_fu_916_p3;
wire   [9:0] xor_ln414_1_fu_932_p2;
wire   [511:0] zext_ln215_fu_884_p1;
wire   [511:0] zext_ln414_fu_938_p1;
wire   [511:0] shl_ln414_fu_950_p2;
reg   [511:0] tmp_3_fu_956_p4;
wire   [511:0] zext_ln414_1_fu_942_p1;
wire   [511:0] zext_ln414_2_fu_946_p1;
wire   [511:0] shl_ln414_1_fu_974_p2;
wire   [511:0] lshr_ln414_fu_980_p2;
wire   [511:0] and_ln414_fu_986_p2;
wire   [511:0] din_data_V_16_fu_854_p3;
wire   [511:0] xor_ln414_2_fu_992_p2;
wire   [511:0] select_ln414_3_fu_966_p3;
wire   [511:0] and_ln414_1_fu_998_p2;
wire   [511:0] and_ln414_2_fu_1004_p2;
wire   [31:0] p_Result_3_fu_1016_p5;
wire   [9:0] trunc_ln414_2_fu_1038_p1;
wire   [0:0] icmp_ln414_1_fu_1032_p2;
wire   [9:0] trunc_ln414_3_fu_1042_p1;
wire   [9:0] xor_ln414_3_fu_1046_p2;
wire   [9:0] select_ln414_4_fu_1052_p3;
wire   [9:0] select_ln414_6_fu_1068_p3;
wire   [9:0] select_ln414_5_fu_1060_p3;
wire   [9:0] xor_ln414_4_fu_1076_p2;
wire   [511:0] zext_ln215_1_fu_1028_p1;
wire   [511:0] zext_ln414_3_fu_1082_p1;
wire   [511:0] shl_ln414_2_fu_1094_p2;
reg   [511:0] tmp_5_fu_1100_p4;
wire   [511:0] zext_ln414_4_fu_1086_p1;
wire   [511:0] zext_ln414_5_fu_1090_p1;
wire   [511:0] shl_ln414_3_fu_1118_p2;
wire   [511:0] lshr_ln414_1_fu_1124_p2;
wire   [511:0] and_ln414_3_fu_1130_p2;
wire   [511:0] xor_ln414_5_fu_1136_p2;
wire   [511:0] select_ln414_7_fu_1110_p3;
wire   [511:0] and_ln414_4_fu_1142_p2;
wire   [511:0] and_ln414_5_fu_1148_p2;
wire   [0:0] icmp_ln53_fu_1160_p2;
wire   [0:0] icmp_ln53_1_fu_1166_p2;
wire   [0:0] icmp_ln870_fu_870_p2;
wire   [0:0] and_ln870_fu_1172_p2;
wire   [0:0] and_ln870_1_fu_1178_p2;
wire   [511:0] p_Result_4_fu_1154_p2;
wire   [0:0] icmp_ln53_2_fu_1192_p2;
wire   [0:0] icmp_ln53_3_fu_1198_p2;
wire   [0:0] icmp_ln53_4_fu_1204_p2;
wire   [0:0] or_ln53_1_fu_1216_p2;
wire   [0:0] or_ln53_fu_1210_p2;
wire   [0:0] or_ln53_2_fu_1222_p2;
wire   [511:0] p_Result_2_fu_1010_p2;
wire   [511:0] din_data_V_7_fu_1184_p3;
wire   [7:0] p_Result_31_i_i_fu_1236_p4;
wire   [15:0] p_Result_5_fu_1246_p5;
wire   [7:0] p_Result_33_i_i_fu_1258_p4;
wire   [511:0] din_data_V_17_fu_1228_p3;
wire   [15:0] p_Result_6_fu_1268_p5;
wire   [7:0] p_Result_36_i_i_fu_1292_p4;
wire   [15:0] p_Result_8_fu_1302_p5;
wire   [7:0] trunc_ln674_1_fu_1314_p1;
wire   [511:0] p_Result_7_fu_1280_p5;
wire   [15:0] p_Result_9_fu_1318_p5;
wire   [2:0] or_ln_fu_1342_p3;
wire   [15:0] zext_ln691_fu_1350_p1;
wire   [15:0] tmp_payload_len_V_fu_444_p4;
wire   [7:0] retval_0_i_i1_i_i_fu_1360_p257;
wire   [7:0] retval_0_i_i1_i_i_fu_1360_p258;
wire   [8:0] zext_ln691_1_fu_1878_p1;
wire   [8:0] add_ln691_fu_1882_p2;
wire   [15:0] zext_ln691_2_fu_1888_p1;
wire   [15:0] udp_len_V_fu_1354_p2;
wire   [15:0] udp_len_V_3_fu_1892_p2;
wire   [7:0] p_Result_41_i_i_fu_1898_p4;
wire   [15:0] p_Result_11_fu_1908_p5;
wire   [7:0] trunc_ln674_2_fu_1920_p1;
wire   [511:0] p_Result_10_fu_1330_p5;
wire   [15:0] p_Result_12_fu_1924_p5;
wire   [511:0] p_Result_13_fu_1936_p5;
wire   [511:0] p_Result_14_fu_1948_p5;
wire   [8:0] zext_ln41_fu_612_p1;
wire   [8:0] add_ln11_fu_1972_p2;
wire   [0:0] icmp_ln11_fu_1978_p2;
wire   [0:0] xor_ln11_fu_1984_p2;
wire   [511:0] p_Result_15_fu_1960_p5;
wire   [0:0] or_ln11_fu_1990_p2;
wire   [511:0] p_Result_16_fu_1996_p5;
wire   [7:0] retval_0_i_i_i_i_fu_2016_p257;
wire   [7:0] retval_0_i_i_i_i_fu_2016_p258;
wire   [8:0] zext_ln691_3_fu_2534_p1;
wire   [8:0] add_ln691_2_fu_2538_p2;
wire   [15:0] zext_ln691_4_fu_2544_p1;
wire   [31:0] frame_ctx_remote_ip_1_fu_472_p4;
wire   [7:0] trunc_ln674_4_fu_2594_p1;
wire   [7:0] p_Result_51_i_i_fu_2584_p4;
wire   [7:0] trunc_ln674_3_fu_2564_p1;
wire   [7:0] p_Result_49_i_i_fu_2554_p4;
wire   [511:0] din_data_V_18_fu_2008_p3;
wire   [143:0] tmp_6_i_i_fu_2598_p8;
wire   [576:0] dout_fu_2655_p3;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_condition_64;
reg    ap_condition_114;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ls_firstWord_1 = 1'd1;
#0 id = 16'd1;
#0 packet_len_preg = 32'd0;
end

tx_rdma_hdr_mux_2568_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 8 ),
    .din65_WIDTH( 8 ),
    .din66_WIDTH( 8 ),
    .din67_WIDTH( 8 ),
    .din68_WIDTH( 8 ),
    .din69_WIDTH( 8 ),
    .din70_WIDTH( 8 ),
    .din71_WIDTH( 8 ),
    .din72_WIDTH( 8 ),
    .din73_WIDTH( 8 ),
    .din74_WIDTH( 8 ),
    .din75_WIDTH( 8 ),
    .din76_WIDTH( 8 ),
    .din77_WIDTH( 8 ),
    .din78_WIDTH( 8 ),
    .din79_WIDTH( 8 ),
    .din80_WIDTH( 8 ),
    .din81_WIDTH( 8 ),
    .din82_WIDTH( 8 ),
    .din83_WIDTH( 8 ),
    .din84_WIDTH( 8 ),
    .din85_WIDTH( 8 ),
    .din86_WIDTH( 8 ),
    .din87_WIDTH( 8 ),
    .din88_WIDTH( 8 ),
    .din89_WIDTH( 8 ),
    .din90_WIDTH( 8 ),
    .din91_WIDTH( 8 ),
    .din92_WIDTH( 8 ),
    .din93_WIDTH( 8 ),
    .din94_WIDTH( 8 ),
    .din95_WIDTH( 8 ),
    .din96_WIDTH( 8 ),
    .din97_WIDTH( 8 ),
    .din98_WIDTH( 8 ),
    .din99_WIDTH( 8 ),
    .din100_WIDTH( 8 ),
    .din101_WIDTH( 8 ),
    .din102_WIDTH( 8 ),
    .din103_WIDTH( 8 ),
    .din104_WIDTH( 8 ),
    .din105_WIDTH( 8 ),
    .din106_WIDTH( 8 ),
    .din107_WIDTH( 8 ),
    .din108_WIDTH( 8 ),
    .din109_WIDTH( 8 ),
    .din110_WIDTH( 8 ),
    .din111_WIDTH( 8 ),
    .din112_WIDTH( 8 ),
    .din113_WIDTH( 8 ),
    .din114_WIDTH( 8 ),
    .din115_WIDTH( 8 ),
    .din116_WIDTH( 8 ),
    .din117_WIDTH( 8 ),
    .din118_WIDTH( 8 ),
    .din119_WIDTH( 8 ),
    .din120_WIDTH( 8 ),
    .din121_WIDTH( 8 ),
    .din122_WIDTH( 8 ),
    .din123_WIDTH( 8 ),
    .din124_WIDTH( 8 ),
    .din125_WIDTH( 8 ),
    .din126_WIDTH( 8 ),
    .din127_WIDTH( 8 ),
    .din128_WIDTH( 8 ),
    .din129_WIDTH( 8 ),
    .din130_WIDTH( 8 ),
    .din131_WIDTH( 8 ),
    .din132_WIDTH( 8 ),
    .din133_WIDTH( 8 ),
    .din134_WIDTH( 8 ),
    .din135_WIDTH( 8 ),
    .din136_WIDTH( 8 ),
    .din137_WIDTH( 8 ),
    .din138_WIDTH( 8 ),
    .din139_WIDTH( 8 ),
    .din140_WIDTH( 8 ),
    .din141_WIDTH( 8 ),
    .din142_WIDTH( 8 ),
    .din143_WIDTH( 8 ),
    .din144_WIDTH( 8 ),
    .din145_WIDTH( 8 ),
    .din146_WIDTH( 8 ),
    .din147_WIDTH( 8 ),
    .din148_WIDTH( 8 ),
    .din149_WIDTH( 8 ),
    .din150_WIDTH( 8 ),
    .din151_WIDTH( 8 ),
    .din152_WIDTH( 8 ),
    .din153_WIDTH( 8 ),
    .din154_WIDTH( 8 ),
    .din155_WIDTH( 8 ),
    .din156_WIDTH( 8 ),
    .din157_WIDTH( 8 ),
    .din158_WIDTH( 8 ),
    .din159_WIDTH( 8 ),
    .din160_WIDTH( 8 ),
    .din161_WIDTH( 8 ),
    .din162_WIDTH( 8 ),
    .din163_WIDTH( 8 ),
    .din164_WIDTH( 8 ),
    .din165_WIDTH( 8 ),
    .din166_WIDTH( 8 ),
    .din167_WIDTH( 8 ),
    .din168_WIDTH( 8 ),
    .din169_WIDTH( 8 ),
    .din170_WIDTH( 8 ),
    .din171_WIDTH( 8 ),
    .din172_WIDTH( 8 ),
    .din173_WIDTH( 8 ),
    .din174_WIDTH( 8 ),
    .din175_WIDTH( 8 ),
    .din176_WIDTH( 8 ),
    .din177_WIDTH( 8 ),
    .din178_WIDTH( 8 ),
    .din179_WIDTH( 8 ),
    .din180_WIDTH( 8 ),
    .din181_WIDTH( 8 ),
    .din182_WIDTH( 8 ),
    .din183_WIDTH( 8 ),
    .din184_WIDTH( 8 ),
    .din185_WIDTH( 8 ),
    .din186_WIDTH( 8 ),
    .din187_WIDTH( 8 ),
    .din188_WIDTH( 8 ),
    .din189_WIDTH( 8 ),
    .din190_WIDTH( 8 ),
    .din191_WIDTH( 8 ),
    .din192_WIDTH( 8 ),
    .din193_WIDTH( 8 ),
    .din194_WIDTH( 8 ),
    .din195_WIDTH( 8 ),
    .din196_WIDTH( 8 ),
    .din197_WIDTH( 8 ),
    .din198_WIDTH( 8 ),
    .din199_WIDTH( 8 ),
    .din200_WIDTH( 8 ),
    .din201_WIDTH( 8 ),
    .din202_WIDTH( 8 ),
    .din203_WIDTH( 8 ),
    .din204_WIDTH( 8 ),
    .din205_WIDTH( 8 ),
    .din206_WIDTH( 8 ),
    .din207_WIDTH( 8 ),
    .din208_WIDTH( 8 ),
    .din209_WIDTH( 8 ),
    .din210_WIDTH( 8 ),
    .din211_WIDTH( 8 ),
    .din212_WIDTH( 8 ),
    .din213_WIDTH( 8 ),
    .din214_WIDTH( 8 ),
    .din215_WIDTH( 8 ),
    .din216_WIDTH( 8 ),
    .din217_WIDTH( 8 ),
    .din218_WIDTH( 8 ),
    .din219_WIDTH( 8 ),
    .din220_WIDTH( 8 ),
    .din221_WIDTH( 8 ),
    .din222_WIDTH( 8 ),
    .din223_WIDTH( 8 ),
    .din224_WIDTH( 8 ),
    .din225_WIDTH( 8 ),
    .din226_WIDTH( 8 ),
    .din227_WIDTH( 8 ),
    .din228_WIDTH( 8 ),
    .din229_WIDTH( 8 ),
    .din230_WIDTH( 8 ),
    .din231_WIDTH( 8 ),
    .din232_WIDTH( 8 ),
    .din233_WIDTH( 8 ),
    .din234_WIDTH( 8 ),
    .din235_WIDTH( 8 ),
    .din236_WIDTH( 8 ),
    .din237_WIDTH( 8 ),
    .din238_WIDTH( 8 ),
    .din239_WIDTH( 8 ),
    .din240_WIDTH( 8 ),
    .din241_WIDTH( 8 ),
    .din242_WIDTH( 8 ),
    .din243_WIDTH( 8 ),
    .din244_WIDTH( 8 ),
    .din245_WIDTH( 8 ),
    .din246_WIDTH( 8 ),
    .din247_WIDTH( 8 ),
    .din248_WIDTH( 8 ),
    .din249_WIDTH( 8 ),
    .din250_WIDTH( 8 ),
    .din251_WIDTH( 8 ),
    .din252_WIDTH( 8 ),
    .din253_WIDTH( 8 ),
    .din254_WIDTH( 8 ),
    .din255_WIDTH( 8 ),
    .din256_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mux_2568_8_1_1_U15(
    .din0(8'd12),
    .din1(8'd12),
    .din2(8'd12),
    .din3(8'd16),
    .din4(8'd12),
    .din5(8'd16),
    .din6(8'd28),
    .din7(8'd12),
    .din8(8'd12),
    .din9(8'd16),
    .din10(8'd28),
    .din11(8'd32),
    .din12(8'd28),
    .din13(8'd16),
    .din14(8'd12),
    .din15(8'd16),
    .din16(8'd16),
    .din17(8'd16),
    .din18(8'd16),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd0),
    .din22(8'd16),
    .din23(8'd16),
    .din24(8'd0),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd0),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd0),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd0),
    .din52(8'd0),
    .din53(8'd0),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd0),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd0),
    .din64(8'd0),
    .din65(8'd0),
    .din66(8'd0),
    .din67(8'd0),
    .din68(8'd0),
    .din69(8'd0),
    .din70(8'd0),
    .din71(8'd0),
    .din72(8'd0),
    .din73(8'd0),
    .din74(8'd0),
    .din75(8'd0),
    .din76(8'd0),
    .din77(8'd0),
    .din78(8'd0),
    .din79(8'd0),
    .din80(8'd0),
    .din81(8'd0),
    .din82(8'd0),
    .din83(8'd0),
    .din84(8'd0),
    .din85(8'd0),
    .din86(8'd0),
    .din87(8'd0),
    .din88(8'd0),
    .din89(8'd0),
    .din90(8'd0),
    .din91(8'd0),
    .din92(8'd0),
    .din93(8'd0),
    .din94(8'd0),
    .din95(8'd0),
    .din96(8'd0),
    .din97(8'd0),
    .din98(8'd0),
    .din99(8'd0),
    .din100(8'd0),
    .din101(8'd0),
    .din102(8'd0),
    .din103(8'd0),
    .din104(8'd0),
    .din105(8'd0),
    .din106(8'd0),
    .din107(8'd0),
    .din108(8'd0),
    .din109(8'd0),
    .din110(8'd0),
    .din111(8'd0),
    .din112(8'd0),
    .din113(8'd0),
    .din114(8'd0),
    .din115(8'd0),
    .din116(8'd0),
    .din117(8'd0),
    .din118(8'd0),
    .din119(8'd0),
    .din120(8'd0),
    .din121(8'd0),
    .din122(8'd0),
    .din123(8'd0),
    .din124(8'd0),
    .din125(8'd0),
    .din126(8'd0),
    .din127(8'd0),
    .din128(8'd0),
    .din129(8'd0),
    .din130(8'd0),
    .din131(8'd0),
    .din132(8'd0),
    .din133(8'd0),
    .din134(8'd0),
    .din135(8'd0),
    .din136(8'd0),
    .din137(8'd0),
    .din138(8'd0),
    .din139(8'd0),
    .din140(8'd0),
    .din141(8'd0),
    .din142(8'd0),
    .din143(8'd0),
    .din144(8'd0),
    .din145(8'd0),
    .din146(8'd0),
    .din147(8'd0),
    .din148(8'd0),
    .din149(8'd0),
    .din150(8'd0),
    .din151(8'd0),
    .din152(8'd0),
    .din153(8'd0),
    .din154(8'd0),
    .din155(8'd0),
    .din156(8'd0),
    .din157(8'd0),
    .din158(8'd0),
    .din159(8'd0),
    .din160(8'd0),
    .din161(8'd0),
    .din162(8'd0),
    .din163(8'd0),
    .din164(8'd0),
    .din165(8'd0),
    .din166(8'd0),
    .din167(8'd0),
    .din168(8'd0),
    .din169(8'd0),
    .din170(8'd0),
    .din171(8'd0),
    .din172(8'd0),
    .din173(8'd0),
    .din174(8'd0),
    .din175(8'd0),
    .din176(8'd0),
    .din177(8'd0),
    .din178(8'd0),
    .din179(8'd0),
    .din180(8'd0),
    .din181(8'd0),
    .din182(8'd0),
    .din183(8'd0),
    .din184(8'd0),
    .din185(8'd0),
    .din186(8'd0),
    .din187(8'd0),
    .din188(8'd0),
    .din189(8'd0),
    .din190(8'd0),
    .din191(8'd0),
    .din192(8'd0),
    .din193(8'd0),
    .din194(8'd0),
    .din195(8'd0),
    .din196(8'd0),
    .din197(8'd0),
    .din198(8'd0),
    .din199(8'd0),
    .din200(8'd0),
    .din201(8'd0),
    .din202(8'd0),
    .din203(8'd0),
    .din204(8'd0),
    .din205(8'd0),
    .din206(8'd0),
    .din207(8'd0),
    .din208(8'd0),
    .din209(8'd0),
    .din210(8'd0),
    .din211(8'd0),
    .din212(8'd0),
    .din213(8'd0),
    .din214(8'd0),
    .din215(8'd0),
    .din216(8'd0),
    .din217(8'd0),
    .din218(8'd0),
    .din219(8'd0),
    .din220(8'd0),
    .din221(8'd0),
    .din222(8'd0),
    .din223(8'd0),
    .din224(8'd0),
    .din225(8'd0),
    .din226(8'd0),
    .din227(8'd0),
    .din228(8'd0),
    .din229(8'd0),
    .din230(8'd0),
    .din231(8'd0),
    .din232(8'd0),
    .din233(8'd0),
    .din234(8'd0),
    .din235(8'd0),
    .din236(8'd0),
    .din237(8'd0),
    .din238(8'd0),
    .din239(8'd0),
    .din240(8'd0),
    .din241(8'd0),
    .din242(8'd0),
    .din243(8'd0),
    .din244(8'd0),
    .din245(8'd0),
    .din246(8'd0),
    .din247(8'd0),
    .din248(8'd0),
    .din249(8'd0),
    .din250(8'd0),
    .din251(8'd0),
    .din252(8'd0),
    .din253(8'd0),
    .din254(8'd0),
    .din255(8'd0),
    .din256(retval_0_i_i1_i_i_fu_1360_p257),
    .dout(retval_0_i_i1_i_i_fu_1360_p258)
);

tx_rdma_hdr_mux_2568_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 8 ),
    .din65_WIDTH( 8 ),
    .din66_WIDTH( 8 ),
    .din67_WIDTH( 8 ),
    .din68_WIDTH( 8 ),
    .din69_WIDTH( 8 ),
    .din70_WIDTH( 8 ),
    .din71_WIDTH( 8 ),
    .din72_WIDTH( 8 ),
    .din73_WIDTH( 8 ),
    .din74_WIDTH( 8 ),
    .din75_WIDTH( 8 ),
    .din76_WIDTH( 8 ),
    .din77_WIDTH( 8 ),
    .din78_WIDTH( 8 ),
    .din79_WIDTH( 8 ),
    .din80_WIDTH( 8 ),
    .din81_WIDTH( 8 ),
    .din82_WIDTH( 8 ),
    .din83_WIDTH( 8 ),
    .din84_WIDTH( 8 ),
    .din85_WIDTH( 8 ),
    .din86_WIDTH( 8 ),
    .din87_WIDTH( 8 ),
    .din88_WIDTH( 8 ),
    .din89_WIDTH( 8 ),
    .din90_WIDTH( 8 ),
    .din91_WIDTH( 8 ),
    .din92_WIDTH( 8 ),
    .din93_WIDTH( 8 ),
    .din94_WIDTH( 8 ),
    .din95_WIDTH( 8 ),
    .din96_WIDTH( 8 ),
    .din97_WIDTH( 8 ),
    .din98_WIDTH( 8 ),
    .din99_WIDTH( 8 ),
    .din100_WIDTH( 8 ),
    .din101_WIDTH( 8 ),
    .din102_WIDTH( 8 ),
    .din103_WIDTH( 8 ),
    .din104_WIDTH( 8 ),
    .din105_WIDTH( 8 ),
    .din106_WIDTH( 8 ),
    .din107_WIDTH( 8 ),
    .din108_WIDTH( 8 ),
    .din109_WIDTH( 8 ),
    .din110_WIDTH( 8 ),
    .din111_WIDTH( 8 ),
    .din112_WIDTH( 8 ),
    .din113_WIDTH( 8 ),
    .din114_WIDTH( 8 ),
    .din115_WIDTH( 8 ),
    .din116_WIDTH( 8 ),
    .din117_WIDTH( 8 ),
    .din118_WIDTH( 8 ),
    .din119_WIDTH( 8 ),
    .din120_WIDTH( 8 ),
    .din121_WIDTH( 8 ),
    .din122_WIDTH( 8 ),
    .din123_WIDTH( 8 ),
    .din124_WIDTH( 8 ),
    .din125_WIDTH( 8 ),
    .din126_WIDTH( 8 ),
    .din127_WIDTH( 8 ),
    .din128_WIDTH( 8 ),
    .din129_WIDTH( 8 ),
    .din130_WIDTH( 8 ),
    .din131_WIDTH( 8 ),
    .din132_WIDTH( 8 ),
    .din133_WIDTH( 8 ),
    .din134_WIDTH( 8 ),
    .din135_WIDTH( 8 ),
    .din136_WIDTH( 8 ),
    .din137_WIDTH( 8 ),
    .din138_WIDTH( 8 ),
    .din139_WIDTH( 8 ),
    .din140_WIDTH( 8 ),
    .din141_WIDTH( 8 ),
    .din142_WIDTH( 8 ),
    .din143_WIDTH( 8 ),
    .din144_WIDTH( 8 ),
    .din145_WIDTH( 8 ),
    .din146_WIDTH( 8 ),
    .din147_WIDTH( 8 ),
    .din148_WIDTH( 8 ),
    .din149_WIDTH( 8 ),
    .din150_WIDTH( 8 ),
    .din151_WIDTH( 8 ),
    .din152_WIDTH( 8 ),
    .din153_WIDTH( 8 ),
    .din154_WIDTH( 8 ),
    .din155_WIDTH( 8 ),
    .din156_WIDTH( 8 ),
    .din157_WIDTH( 8 ),
    .din158_WIDTH( 8 ),
    .din159_WIDTH( 8 ),
    .din160_WIDTH( 8 ),
    .din161_WIDTH( 8 ),
    .din162_WIDTH( 8 ),
    .din163_WIDTH( 8 ),
    .din164_WIDTH( 8 ),
    .din165_WIDTH( 8 ),
    .din166_WIDTH( 8 ),
    .din167_WIDTH( 8 ),
    .din168_WIDTH( 8 ),
    .din169_WIDTH( 8 ),
    .din170_WIDTH( 8 ),
    .din171_WIDTH( 8 ),
    .din172_WIDTH( 8 ),
    .din173_WIDTH( 8 ),
    .din174_WIDTH( 8 ),
    .din175_WIDTH( 8 ),
    .din176_WIDTH( 8 ),
    .din177_WIDTH( 8 ),
    .din178_WIDTH( 8 ),
    .din179_WIDTH( 8 ),
    .din180_WIDTH( 8 ),
    .din181_WIDTH( 8 ),
    .din182_WIDTH( 8 ),
    .din183_WIDTH( 8 ),
    .din184_WIDTH( 8 ),
    .din185_WIDTH( 8 ),
    .din186_WIDTH( 8 ),
    .din187_WIDTH( 8 ),
    .din188_WIDTH( 8 ),
    .din189_WIDTH( 8 ),
    .din190_WIDTH( 8 ),
    .din191_WIDTH( 8 ),
    .din192_WIDTH( 8 ),
    .din193_WIDTH( 8 ),
    .din194_WIDTH( 8 ),
    .din195_WIDTH( 8 ),
    .din196_WIDTH( 8 ),
    .din197_WIDTH( 8 ),
    .din198_WIDTH( 8 ),
    .din199_WIDTH( 8 ),
    .din200_WIDTH( 8 ),
    .din201_WIDTH( 8 ),
    .din202_WIDTH( 8 ),
    .din203_WIDTH( 8 ),
    .din204_WIDTH( 8 ),
    .din205_WIDTH( 8 ),
    .din206_WIDTH( 8 ),
    .din207_WIDTH( 8 ),
    .din208_WIDTH( 8 ),
    .din209_WIDTH( 8 ),
    .din210_WIDTH( 8 ),
    .din211_WIDTH( 8 ),
    .din212_WIDTH( 8 ),
    .din213_WIDTH( 8 ),
    .din214_WIDTH( 8 ),
    .din215_WIDTH( 8 ),
    .din216_WIDTH( 8 ),
    .din217_WIDTH( 8 ),
    .din218_WIDTH( 8 ),
    .din219_WIDTH( 8 ),
    .din220_WIDTH( 8 ),
    .din221_WIDTH( 8 ),
    .din222_WIDTH( 8 ),
    .din223_WIDTH( 8 ),
    .din224_WIDTH( 8 ),
    .din225_WIDTH( 8 ),
    .din226_WIDTH( 8 ),
    .din227_WIDTH( 8 ),
    .din228_WIDTH( 8 ),
    .din229_WIDTH( 8 ),
    .din230_WIDTH( 8 ),
    .din231_WIDTH( 8 ),
    .din232_WIDTH( 8 ),
    .din233_WIDTH( 8 ),
    .din234_WIDTH( 8 ),
    .din235_WIDTH( 8 ),
    .din236_WIDTH( 8 ),
    .din237_WIDTH( 8 ),
    .din238_WIDTH( 8 ),
    .din239_WIDTH( 8 ),
    .din240_WIDTH( 8 ),
    .din241_WIDTH( 8 ),
    .din242_WIDTH( 8 ),
    .din243_WIDTH( 8 ),
    .din244_WIDTH( 8 ),
    .din245_WIDTH( 8 ),
    .din246_WIDTH( 8 ),
    .din247_WIDTH( 8 ),
    .din248_WIDTH( 8 ),
    .din249_WIDTH( 8 ),
    .din250_WIDTH( 8 ),
    .din251_WIDTH( 8 ),
    .din252_WIDTH( 8 ),
    .din253_WIDTH( 8 ),
    .din254_WIDTH( 8 ),
    .din255_WIDTH( 8 ),
    .din256_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mux_2568_8_1_1_U16(
    .din0(8'd12),
    .din1(8'd12),
    .din2(8'd12),
    .din3(8'd16),
    .din4(8'd12),
    .din5(8'd16),
    .din6(8'd28),
    .din7(8'd12),
    .din8(8'd12),
    .din9(8'd16),
    .din10(8'd28),
    .din11(8'd32),
    .din12(8'd28),
    .din13(8'd16),
    .din14(8'd12),
    .din15(8'd16),
    .din16(8'd16),
    .din17(8'd16),
    .din18(8'd16),
    .din19(8'd0),
    .din20(8'd0),
    .din21(8'd0),
    .din22(8'd16),
    .din23(8'd16),
    .din24(8'd0),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd0),
    .din33(8'd0),
    .din34(8'd0),
    .din35(8'd0),
    .din36(8'd0),
    .din37(8'd0),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd0),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd0),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd0),
    .din52(8'd0),
    .din53(8'd0),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd0),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd0),
    .din62(8'd0),
    .din63(8'd0),
    .din64(8'd0),
    .din65(8'd0),
    .din66(8'd0),
    .din67(8'd0),
    .din68(8'd0),
    .din69(8'd0),
    .din70(8'd0),
    .din71(8'd0),
    .din72(8'd0),
    .din73(8'd0),
    .din74(8'd0),
    .din75(8'd0),
    .din76(8'd0),
    .din77(8'd0),
    .din78(8'd0),
    .din79(8'd0),
    .din80(8'd0),
    .din81(8'd0),
    .din82(8'd0),
    .din83(8'd0),
    .din84(8'd0),
    .din85(8'd0),
    .din86(8'd0),
    .din87(8'd0),
    .din88(8'd0),
    .din89(8'd0),
    .din90(8'd0),
    .din91(8'd0),
    .din92(8'd0),
    .din93(8'd0),
    .din94(8'd0),
    .din95(8'd0),
    .din96(8'd0),
    .din97(8'd0),
    .din98(8'd0),
    .din99(8'd0),
    .din100(8'd0),
    .din101(8'd0),
    .din102(8'd0),
    .din103(8'd0),
    .din104(8'd0),
    .din105(8'd0),
    .din106(8'd0),
    .din107(8'd0),
    .din108(8'd0),
    .din109(8'd0),
    .din110(8'd0),
    .din111(8'd0),
    .din112(8'd0),
    .din113(8'd0),
    .din114(8'd0),
    .din115(8'd0),
    .din116(8'd0),
    .din117(8'd0),
    .din118(8'd0),
    .din119(8'd0),
    .din120(8'd0),
    .din121(8'd0),
    .din122(8'd0),
    .din123(8'd0),
    .din124(8'd0),
    .din125(8'd0),
    .din126(8'd0),
    .din127(8'd0),
    .din128(8'd0),
    .din129(8'd0),
    .din130(8'd0),
    .din131(8'd0),
    .din132(8'd0),
    .din133(8'd0),
    .din134(8'd0),
    .din135(8'd0),
    .din136(8'd0),
    .din137(8'd0),
    .din138(8'd0),
    .din139(8'd0),
    .din140(8'd0),
    .din141(8'd0),
    .din142(8'd0),
    .din143(8'd0),
    .din144(8'd0),
    .din145(8'd0),
    .din146(8'd0),
    .din147(8'd0),
    .din148(8'd0),
    .din149(8'd0),
    .din150(8'd0),
    .din151(8'd0),
    .din152(8'd0),
    .din153(8'd0),
    .din154(8'd0),
    .din155(8'd0),
    .din156(8'd0),
    .din157(8'd0),
    .din158(8'd0),
    .din159(8'd0),
    .din160(8'd0),
    .din161(8'd0),
    .din162(8'd0),
    .din163(8'd0),
    .din164(8'd0),
    .din165(8'd0),
    .din166(8'd0),
    .din167(8'd0),
    .din168(8'd0),
    .din169(8'd0),
    .din170(8'd0),
    .din171(8'd0),
    .din172(8'd0),
    .din173(8'd0),
    .din174(8'd0),
    .din175(8'd0),
    .din176(8'd0),
    .din177(8'd0),
    .din178(8'd0),
    .din179(8'd0),
    .din180(8'd0),
    .din181(8'd0),
    .din182(8'd0),
    .din183(8'd0),
    .din184(8'd0),
    .din185(8'd0),
    .din186(8'd0),
    .din187(8'd0),
    .din188(8'd0),
    .din189(8'd0),
    .din190(8'd0),
    .din191(8'd0),
    .din192(8'd0),
    .din193(8'd0),
    .din194(8'd0),
    .din195(8'd0),
    .din196(8'd0),
    .din197(8'd0),
    .din198(8'd0),
    .din199(8'd0),
    .din200(8'd0),
    .din201(8'd0),
    .din202(8'd0),
    .din203(8'd0),
    .din204(8'd0),
    .din205(8'd0),
    .din206(8'd0),
    .din207(8'd0),
    .din208(8'd0),
    .din209(8'd0),
    .din210(8'd0),
    .din211(8'd0),
    .din212(8'd0),
    .din213(8'd0),
    .din214(8'd0),
    .din215(8'd0),
    .din216(8'd0),
    .din217(8'd0),
    .din218(8'd0),
    .din219(8'd0),
    .din220(8'd0),
    .din221(8'd0),
    .din222(8'd0),
    .din223(8'd0),
    .din224(8'd0),
    .din225(8'd0),
    .din226(8'd0),
    .din227(8'd0),
    .din228(8'd0),
    .din229(8'd0),
    .din230(8'd0),
    .din231(8'd0),
    .din232(8'd0),
    .din233(8'd0),
    .din234(8'd0),
    .din235(8'd0),
    .din236(8'd0),
    .din237(8'd0),
    .din238(8'd0),
    .din239(8'd0),
    .din240(8'd0),
    .din241(8'd0),
    .din242(8'd0),
    .din243(8'd0),
    .din244(8'd0),
    .din245(8'd0),
    .din246(8'd0),
    .din247(8'd0),
    .din248(8'd0),
    .din249(8'd0),
    .din250(8'd0),
    .din251(8'd0),
    .din252(8'd0),
    .din253(8'd0),
    .din254(8'd0),
    .din255(8'd0),
    .din256(retval_0_i_i_i_i_fu_2016_p257),
    .dout(retval_0_i_i_i_i_fu_2016_p258)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                packet_len_preg[0] <= 1'b0;
        packet_len_preg[1] <= 1'b0;
        packet_len_preg[2] <= 1'b0;
        packet_len_preg[3] <= 1'b0;
        packet_len_preg[4] <= 1'b0;
        packet_len_preg[5] <= 1'b0;
        packet_len_preg[6] <= 1'b0;
        packet_len_preg[7] <= 1'b0;
        packet_len_preg[8] <= 1'b0;
        packet_len_preg[9] <= 1'b0;
        packet_len_preg[10] <= 1'b0;
        packet_len_preg[11] <= 1'b0;
        packet_len_preg[12] <= 1'b0;
        packet_len_preg[13] <= 1'b0;
        packet_len_preg[14] <= 1'b0;
        packet_len_preg[15] <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & (tmp_1_i_i_reg_2675 == 1'd1) & (ls_firstWord_1_load_reg_2671 == 1'd1) & (tmp_i_i_reg_2667 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                        packet_len_preg[15 : 0] <= zext_ln208_fu_2651_p1[15 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_114)) begin
        if (((ls_firstWord_1 == 1'd0) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_din_data_V_reg_418 <= tmp_data_V_1_fu_431_p1;
        end else if ((1'b1 == ap_condition_64)) begin
            ap_phi_reg_pp0_iter1_din_data_V_reg_418 <= p_Result_17_fu_2616_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_din_data_V_reg_418 <= ap_phi_reg_pp0_iter0_din_data_V_reg_418;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (ls_firstWord_1 == 1'd1) & (tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd1) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        id <= add_ln691_4_fu_2572_p2;
        ip_len_V_reg_2689 <= ip_len_V_fu_2548_p2;
        payload_rem_V_1_reg_2684 <= payload_rem_V_1_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_phi_mux_ls_firstWord_3_flag_1_i_i_phi_fu_395_p6 == 1'd1))) begin
        ls_firstWord_1 <= ap_phi_mux_ls_firstWord_3_new_1_i_i_phi_fu_408_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ls_firstWord_1_load_reg_2671 <= ls_firstWord_1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (ls_firstWord_1 == 1'd1) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_1_i_i_reg_2675 <= tmp_1_i_i_nbreadreq_fu_340_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_i_i_reg_2667 <= tmp_i_i_nbreadreq_fu_332_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (((ls_firstWord_1 == 1'd0) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)) | ((tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd1) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1))))) begin
        tmp_reg_2699 <= {{tx_to_hdr_gen_dout[576:512]}};
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)) begin
        if ((ls_firstWord_1 == 1'd0)) begin
            ap_phi_mux_ls_firstWord_3_flag_0_i_i_phi_fu_384_p4 = 1'd0;
        end else if (((ls_firstWord_1 == 1'd1) & (tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd1))) begin
            ap_phi_mux_ls_firstWord_3_flag_0_i_i_phi_fu_384_p4 = 1'd1;
        end else begin
            ap_phi_mux_ls_firstWord_3_flag_0_i_i_phi_fu_384_p4 = ap_phi_reg_pp0_iter0_ls_firstWord_3_flag_0_i_i_reg_381;
        end
    end else begin
        ap_phi_mux_ls_firstWord_3_flag_0_i_i_phi_fu_384_p4 = ap_phi_reg_pp0_iter0_ls_firstWord_3_flag_0_i_i_reg_381;
    end
end

always @ (*) begin
    if ((((ls_firstWord_1 == 1'd0) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)) | ((tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd1) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)))) begin
        ap_phi_mux_ls_firstWord_3_flag_1_i_i_phi_fu_395_p6 = or_ln454_fu_2638_p2;
    end else if (((tmp_i_i_nbreadreq_fu_332_p3 == 1'd0) | ((ls_firstWord_1 == 1'd1) & (tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd0) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)))) begin
        ap_phi_mux_ls_firstWord_3_flag_1_i_i_phi_fu_395_p6 = 1'd0;
    end else begin
        ap_phi_mux_ls_firstWord_3_flag_1_i_i_phi_fu_395_p6 = ap_phi_reg_pp0_iter0_ls_firstWord_3_flag_1_i_i_reg_392;
    end
end

always @ (*) begin
    if ((((ls_firstWord_1 == 1'd0) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)) | ((tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd1) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)))) begin
        ap_phi_mux_ls_firstWord_3_new_1_i_i_phi_fu_408_p6 = tx_to_hdr_gen_dout[32'd576];
    end else begin
        ap_phi_mux_ls_firstWord_3_new_1_i_i_phi_fu_408_p6 = ap_phi_reg_pp0_iter0_ls_firstWord_3_new_1_i_i_reg_405;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (ap_predicate_op46_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        axis_frame_ctx_to_hdr_gen_blk_n = axis_frame_ctx_to_hdr_gen_empty_n;
    end else begin
        axis_frame_ctx_to_hdr_gen_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (ap_predicate_op46_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        axis_frame_ctx_to_hdr_gen_read = 1'b1;
    end else begin
        axis_frame_ctx_to_hdr_gen_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ecn_for_ack_blk_n = ecn_for_ack_empty_n;
    end else begin
        ecn_for_ack_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ecn_for_ack_read = 1'b1;
    end else begin
        ecn_for_ack_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & (tmp_1_i_i_reg_2675 == 1'd1) & (ls_firstWord_1_load_reg_2671 == 1'd1) & (tmp_i_i_reg_2667 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        packet_len = zext_ln208_fu_2651_p1;
    end else begin
        packet_len = packet_len_preg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & (tmp_1_i_i_reg_2675 == 1'd1) & (ls_firstWord_1_load_reg_2671 == 1'd1) & (tmp_i_i_reg_2667 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        packet_len_ap_vld = 1'b1;
    end else begin
        packet_len_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op203_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        payload_remainder_blk_n = payload_remainder_full_n;
    end else begin
        payload_remainder_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & (ap_predicate_op203_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        payload_remainder_write = 1'b1;
    end else begin
        payload_remainder_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op209_write_state2 == 1'b1))) begin
        tx_to_crc_and_remainder_blk_n = tx_to_crc_and_remainder_full_n;
    end else begin
        tx_to_crc_and_remainder_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op209_write_state2 == 1'b1))) begin
        tx_to_crc_and_remainder_write = 1'b1;
    end else begin
        tx_to_crc_and_remainder_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (ap_predicate_op42_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tx_to_hdr_gen_blk_n = tx_to_hdr_gen_empty_n;
    end else begin
        tx_to_hdr_gen_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (ap_predicate_op42_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tx_to_hdr_gen_read = 1'b1;
    end else begin
        tx_to_hdr_gen_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0))) & ~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln11_fu_1972_p2 = ($signed(zext_ln41_fu_612_p1) + $signed(9'd499));

assign add_ln691_2_fu_2538_p2 = (zext_ln691_3_fu_2534_p1 + 9'd28);

assign add_ln691_4_fu_2572_p2 = (id + 16'd1);

assign add_ln691_fu_1882_p2 = (zext_ln691_1_fu_1878_p1 + 9'd8);

assign and_ln414_1_fu_998_p2 = (xor_ln414_2_fu_992_p2 & din_data_V_16_fu_854_p3);

assign and_ln414_2_fu_1004_p2 = (select_ln414_3_fu_966_p3 & and_ln414_fu_986_p2);

assign and_ln414_3_fu_1130_p2 = (shl_ln414_3_fu_1118_p2 & lshr_ln414_1_fu_1124_p2);

assign and_ln414_4_fu_1142_p2 = (xor_ln414_5_fu_1136_p2 & din_data_V_16_fu_854_p3);

assign and_ln414_5_fu_1148_p2 = (select_ln414_7_fu_1110_p3 & and_ln414_3_fu_1130_p2);

assign and_ln414_fu_986_p2 = (shl_ln414_1_fu_974_p2 & lshr_ln414_fu_980_p2);

assign and_ln870_1_fu_1178_p2 = (icmp_ln870_fu_870_p2 & and_ln870_fu_1172_p2);

assign and_ln870_fu_1172_p2 = (icmp_ln53_fu_1160_p2 & icmp_ln53_1_fu_1166_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_114 = (~((ap_start == 1'b0) | (ecn_for_ack_empty_n == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op46_read_state1 == 1'b1) & (axis_frame_ctx_to_hdr_gen_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (tx_to_hdr_gen_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((tx_to_crc_and_remainder_full_n == 1'b0) & (ap_predicate_op209_write_state2 == 1'b1)) | ((ap_predicate_op203_write_state2 == 1'b1) & (payload_remainder_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_64 = ((ls_firstWord_1 == 1'd1) & (tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd1) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1));
end

assign ap_phi_reg_pp0_iter0_din_data_V_reg_418 = 'bx;

assign ap_phi_reg_pp0_iter0_ls_firstWord_3_flag_0_i_i_reg_381 = 'bx;

assign ap_phi_reg_pp0_iter0_ls_firstWord_3_flag_1_i_i_reg_392 = 'bx;

assign ap_phi_reg_pp0_iter0_ls_firstWord_3_new_1_i_i_reg_405 = 'bx;

always @ (*) begin
    ap_predicate_op203_write_state2 = ((tmp_1_i_i_reg_2675 == 1'd1) & (ls_firstWord_1_load_reg_2671 == 1'd1) & (tmp_i_i_reg_2667 == 1'd1));
end

always @ (*) begin
    ap_predicate_op209_write_state2 = (((ls_firstWord_1_load_reg_2671 == 1'd0) & (tmp_i_i_reg_2667 == 1'd1)) | ((tmp_1_i_i_reg_2675 == 1'd1) & (tmp_i_i_reg_2667 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op42_read_state1 = (((ls_firstWord_1 == 1'd0) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)) | ((tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd1) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op46_read_state1 = ((ls_firstWord_1 == 1'd1) & (tmp_1_i_i_nbreadreq_fu_340_p3 == 1'd1) & (tmp_i_i_nbreadreq_fu_332_p3 == 1'd1));
end

assign din_data_V_16_fu_854_p3 = ((or_ln41_1_fu_848_p2[0:0] == 1'b1) ? p_Result_1_fu_812_p5 : p_Result_s_fu_600_p5);

assign din_data_V_17_fu_1228_p3 = ((or_ln53_2_fu_1222_p2[0:0] == 1'b1) ? p_Result_2_fu_1010_p2 : din_data_V_7_fu_1184_p3);

assign din_data_V_18_fu_2008_p3 = ((or_ln11_fu_1990_p2[0:0] == 1'b1) ? p_Result_15_fu_1960_p5 : p_Result_16_fu_1996_p5);

assign din_data_V_7_fu_1184_p3 = ((and_ln870_1_fu_1178_p2[0:0] == 1'b1) ? p_Result_4_fu_1154_p2 : din_data_V_16_fu_854_p3);

assign dout_fu_2655_p3 = {{tmp_reg_2699}, {ap_phi_reg_pp0_iter1_din_data_V_reg_418}};

assign frame_ctx_explicit_ack_1_fu_464_p3 = axis_frame_ctx_to_hdr_gen_dout[32'd72];

assign frame_ctx_remote_ip_1_fu_472_p4 = {{axis_frame_ctx_to_hdr_gen_dout[104:73]}};

assign icmp_ln11_fu_1978_p2 = ((add_ln11_fu_1972_p2 > 9'd4) ? 1'b1 : 1'b0);

assign icmp_ln414_1_fu_1032_p2 = ((select_ln155_fu_862_p3 > select_ln215_fu_876_p3) ? 1'b1 : 1'b0);

assign icmp_ln414_fu_888_p2 = ((select_ln155_fu_862_p3 > select_ln215_fu_876_p3) ? 1'b1 : 1'b0);

assign icmp_ln41_1_fu_830_p2 = ((tmp_opcode_V_fu_454_p4 == 8'd10) ? 1'b1 : 1'b0);

assign icmp_ln41_2_fu_836_p2 = ((tmp_opcode_V_fu_454_p4 == 8'd6) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_824_p2 = ((tmp_opcode_V_fu_454_p4 == 8'd11) ? 1'b1 : 1'b0);

assign icmp_ln53_1_fu_1166_p2 = ((tmp_opcode_V_fu_454_p4 != 8'd9) ? 1'b1 : 1'b0);

assign icmp_ln53_2_fu_1192_p2 = ((tmp_opcode_V_fu_454_p4 == 8'd9) ? 1'b1 : 1'b0);

assign icmp_ln53_3_fu_1198_p2 = ((tmp_opcode_V_fu_454_p4 == 8'd5) ? 1'b1 : 1'b0);

assign icmp_ln53_4_fu_1204_p2 = ((tmp_opcode_V_fu_454_p4 == 8'd3) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_1160_p2 = ((tmp_opcode_V_fu_454_p4 != 8'd11) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_870_p2 = ((tmp_opcode_V_fu_454_p4 == 8'd17) ? 1'b1 : 1'b0);

assign ip_len_V_fu_2548_p2 = (zext_ln691_4_fu_2544_p1 + udp_len_V_fu_1354_p2);

assign lshr_ln414_1_fu_1124_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln414_5_fu_1090_p1;

assign lshr_ln414_fu_980_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 >> zext_ln414_2_fu_946_p1;

assign or_ln11_fu_1990_p2 = (xor_ln11_fu_1984_p2 | icmp_ln11_fu_1978_p2);

assign or_ln41_1_fu_848_p2 = (or_ln41_fu_842_p2 | icmp_ln41_fu_824_p2);

assign or_ln41_fu_842_p2 = (icmp_ln41_2_fu_836_p2 | icmp_ln41_1_fu_830_p2);

assign or_ln454_fu_2638_p2 = (tmp_last_V_fu_435_p3 | ap_phi_mux_ls_firstWord_3_flag_0_i_i_phi_fu_384_p4);

assign or_ln53_1_fu_1216_p2 = (icmp_ln53_4_fu_1204_p2 | icmp_ln53_3_fu_1198_p2);

assign or_ln53_2_fu_1222_p2 = (or_ln53_fu_1210_p2 | or_ln53_1_fu_1216_p2);

assign or_ln53_fu_1210_p2 = (icmp_ln53_2_fu_1192_p2 | icmp_ln41_fu_824_p2);

assign or_ln_fu_1342_p3 = {{1'd1}, {payload_rem_V_1_fu_502_p2}};

assign p_Result_10_fu_1330_p5 = {{p_Result_7_fu_1280_p5[511:192]}, {p_Result_9_fu_1318_p5}, {p_Result_7_fu_1280_p5[175:0]}};

assign p_Result_10_i_i_fu_646_p4 = {{axis_frame_ctx_to_hdr_gen_dout[152:145]}};

assign p_Result_11_fu_1908_p5 = {{ap_const_lv16_0[15:8]}, {p_Result_41_i_i_fu_1898_p4}};

assign p_Result_11_i_i_fu_656_p4 = {{axis_frame_ctx_to_hdr_gen_dout[160:153]}};

assign p_Result_12_fu_1924_p5 = {{trunc_ln674_2_fu_1920_p1}, {p_Result_11_fu_1908_p5[7:0]}};

assign p_Result_12_i_i_fu_666_p4 = {{axis_frame_ctx_to_hdr_gen_dout[168:161]}};

assign p_Result_13_fu_1936_p5 = {{p_Result_10_fu_1330_p5[511:208]}, {p_Result_12_fu_1924_p5}, {p_Result_10_fu_1330_p5[191:0]}};

assign p_Result_13_i_i_fu_676_p4 = {{axis_frame_ctx_to_hdr_gen_dout[176:169]}};

assign p_Result_14_fu_1948_p5 = {{p_Result_13_fu_1936_p5[511:224]}, {16'd0}, {p_Result_13_fu_1936_p5[207:0]}};

assign p_Result_14_i_i_fu_686_p4 = {{axis_frame_ctx_to_hdr_gen_dout[184:177]}};

assign p_Result_15_fu_1960_p5 = {{p_Result_14_fu_1948_p5[511:16]}, {16'd581}};

assign p_Result_15_i_i_fu_696_p4 = {{axis_frame_ctx_to_hdr_gen_dout[192:185]}};

assign p_Result_16_fu_1996_p5 = {{p_Result_15_fu_1960_p5[511:10]}, {2'd3}, {p_Result_15_fu_1960_p5[7:0]}};

assign p_Result_16_i_i_fu_706_p4 = {{axis_frame_ctx_to_hdr_gen_dout[200:193]}};

assign p_Result_17_fu_2616_p5 = {{din_data_V_18_fu_2008_p3[511:160]}, {tmp_6_i_i_fu_2598_p8}, {din_data_V_18_fu_2008_p3[15:0]}};

assign p_Result_17_i_i_fu_716_p4 = {{axis_frame_ctx_to_hdr_gen_dout[208:201]}};

assign p_Result_18_i_i_fu_726_p4 = {{axis_frame_ctx_to_hdr_gen_dout[216:209]}};

assign p_Result_19_i_i_fu_736_p4 = {{axis_frame_ctx_to_hdr_gen_dout[224:217]}};

assign p_Result_1_fu_812_p5 = {{p_Result_s_fu_600_p5[511:448]}, {tmp_3_i_i_fu_776_p17}, {p_Result_s_fu_600_p5[319:0]}};

assign p_Result_1_i_i_fu_532_p4 = {{axis_frame_ctx_to_hdr_gen_dout[23:16]}};

assign p_Result_20_i_i_fu_746_p4 = {{axis_frame_ctx_to_hdr_gen_dout[232:225]}};

assign p_Result_21_i_i_fu_756_p4 = {{axis_frame_ctx_to_hdr_gen_dout[240:233]}};

assign p_Result_22_i_i_fu_766_p4 = {{axis_frame_ctx_to_hdr_gen_dout[248:241]}};

assign p_Result_2_fu_1010_p2 = (and_ln414_2_fu_1004_p2 | and_ln414_1_fu_998_p2);

assign p_Result_2_i_i_fu_542_p4 = {{axis_frame_ctx_to_hdr_gen_dout[31:24]}};

assign p_Result_31_i_i_fu_1236_p4 = {{axis_frame_ctx_to_hdr_gen_dout[120:113]}};

assign p_Result_33_i_i_fu_1258_p4 = {{axis_frame_ctx_to_hdr_gen_dout[112:105]}};

assign p_Result_36_i_i_fu_1292_p4 = {{rdma_udp_port_dst[15:8]}};

assign p_Result_3_fu_1016_p5 = {{{{p_Result_6_i_i_fu_616_p4}, {p_Result_7_i_i_fu_626_p4}}, {p_Result_8_i_i_fu_636_p4}}, {p_Result_10_i_i_fu_646_p4}};

assign p_Result_3_i_i_fu_552_p4 = {{axis_frame_ctx_to_hdr_gen_dout[39:32]}};

assign p_Result_41_i_i_fu_1898_p4 = {{udp_len_V_3_fu_1892_p2[15:8]}};

assign p_Result_49_i_i_fu_2554_p4 = {{ip_len_V_fu_2548_p2[15:8]}};

assign p_Result_4_fu_1154_p2 = (and_ln414_5_fu_1148_p2 | and_ln414_4_fu_1142_p2);

assign p_Result_4_i_i_fu_562_p4 = {{axis_frame_ctx_to_hdr_gen_dout[47:40]}};

assign p_Result_51_i_i_fu_2584_p4 = {{id[15:8]}};

assign p_Result_5_fu_1246_p5 = {{ap_const_lv16_0[15:8]}, {p_Result_31_i_i_fu_1236_p4}};

assign p_Result_6_fu_1268_p5 = {{p_Result_33_i_i_fu_1258_p4}, {p_Result_5_fu_1246_p5[7:0]}};

assign p_Result_6_i_i_fu_616_p4 = {{axis_frame_ctx_to_hdr_gen_dout[128:121]}};

assign p_Result_7_fu_1280_p5 = {{din_data_V_17_fu_1228_p3[511:176]}, {p_Result_6_fu_1268_p5}, {din_data_V_17_fu_1228_p3[159:0]}};

assign p_Result_7_i_i_fu_626_p4 = {{axis_frame_ctx_to_hdr_gen_dout[136:129]}};

assign p_Result_8_fu_1302_p5 = {{ap_const_lv16_0[15:8]}, {p_Result_36_i_i_fu_1292_p4}};

assign p_Result_8_i_i_fu_636_p4 = {{axis_frame_ctx_to_hdr_gen_dout[144:137]}};

assign p_Result_9_fu_1318_p5 = {{trunc_ln674_1_fu_1314_p1}, {p_Result_8_fu_1302_p5[7:0]}};

assign p_Result_i_i_52_fu_522_p4 = {{axis_frame_ctx_to_hdr_gen_dout[15:8]}};

assign p_Result_i_i_fu_492_p4 = {{axis_frame_ctx_to_hdr_gen_dout[49:48]}};

assign p_Result_s_fu_600_p5 = {{tmp_data_V_1_fu_431_p1[511:320]}, {tmp_2_i_i_fu_572_p13}, {tmp_data_V_1_fu_431_p1[223:0]}};

assign payload_rem_V_1_fu_502_p2 = (2'd0 - p_Result_i_i_fu_492_p4);

assign payload_remainder_din = payload_rem_V_1_reg_2684;

assign retval_0_i_i1_i_i_fu_1360_p257 = {{axis_frame_ctx_to_hdr_gen_dout[71:64]}};

assign retval_0_i_i_i_i_fu_2016_p257 = {{axis_frame_ctx_to_hdr_gen_dout[71:64]}};

assign select_ln155_fu_862_p3 = ((or_ln41_1_fu_848_p2[0:0] == 1'b1) ? 32'd448 : 32'd320);

assign select_ln215_fu_876_p3 = ((or_ln41_1_fu_848_p2[0:0] == 1'b1) ? 32'd479 : 32'd351);

assign select_ln414_1_fu_916_p3 = ((icmp_ln414_fu_888_p2[0:0] == 1'b1) ? trunc_ln414_1_fu_898_p1 : trunc_ln414_fu_894_p1);

assign select_ln414_2_fu_924_p3 = ((icmp_ln414_fu_888_p2[0:0] == 1'b1) ? xor_ln414_fu_902_p2 : trunc_ln414_fu_894_p1);

assign select_ln414_3_fu_966_p3 = ((icmp_ln414_fu_888_p2[0:0] == 1'b1) ? tmp_3_fu_956_p4 : shl_ln414_fu_950_p2);

assign select_ln414_4_fu_1052_p3 = ((icmp_ln414_1_fu_1032_p2[0:0] == 1'b1) ? trunc_ln414_2_fu_1038_p1 : trunc_ln414_3_fu_1042_p1);

assign select_ln414_5_fu_1060_p3 = ((icmp_ln414_1_fu_1032_p2[0:0] == 1'b1) ? trunc_ln414_3_fu_1042_p1 : trunc_ln414_2_fu_1038_p1);

assign select_ln414_6_fu_1068_p3 = ((icmp_ln414_1_fu_1032_p2[0:0] == 1'b1) ? xor_ln414_3_fu_1046_p2 : trunc_ln414_2_fu_1038_p1);

assign select_ln414_7_fu_1110_p3 = ((icmp_ln414_1_fu_1032_p2[0:0] == 1'b1) ? tmp_5_fu_1100_p4 : shl_ln414_2_fu_1094_p2);

assign select_ln414_fu_908_p3 = ((icmp_ln414_fu_888_p2[0:0] == 1'b1) ? trunc_ln414_fu_894_p1 : trunc_ln414_1_fu_898_p1);

assign shl_ln414_1_fu_974_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 << zext_ln414_1_fu_942_p1;

assign shl_ln414_2_fu_1094_p2 = zext_ln215_1_fu_1028_p1 << zext_ln414_3_fu_1082_p1;

assign shl_ln414_3_fu_1118_p2 = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 << zext_ln414_4_fu_1086_p1;

assign shl_ln414_fu_950_p2 = zext_ln215_fu_884_p1 << zext_ln414_fu_938_p1;

assign tmp_1_i_i_nbreadreq_fu_340_p3 = axis_frame_ctx_to_hdr_gen_empty_n;

assign tmp_2_i_i_fu_572_p13 = {{{{{{{{{{{{p_Result_2_i_i_fu_542_p4}, {p_Result_3_i_i_fu_552_p4}}, {p_Result_4_i_i_fu_562_p4}}, {frame_ctx_explicit_ack_1_fu_464_p3}}, {7'd0}}, {trunc_ln674_fu_518_p1}}, {p_Result_i_i_52_fu_522_p4}}, {p_Result_1_i_i_fu_532_p4}}, {26'd262140}}, {payload_rem_V_1_fu_502_p2}}, {7'd0}}, {trunc_ln_fu_508_p4}};

integer ap_tvar_int_0;

always @ (shl_ln414_fu_950_p2) begin
    for (ap_tvar_int_0 = 512 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 511 - 0) begin
            tmp_3_fu_956_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_3_fu_956_p4[ap_tvar_int_0] = shl_ln414_fu_950_p2[511 - ap_tvar_int_0];
        end
    end
end

assign tmp_3_i_i_fu_776_p17 = {{{{{{{{{{{{{{{{p_Result_19_i_i_fu_736_p4}, {p_Result_20_i_i_fu_746_p4}}, {p_Result_21_i_i_fu_756_p4}}, {p_Result_22_i_i_fu_766_p4}}, {p_Result_15_i_i_fu_696_p4}}, {p_Result_16_i_i_fu_706_p4}}, {p_Result_17_i_i_fu_716_p4}}, {p_Result_18_i_i_fu_726_p4}}, {p_Result_11_i_i_fu_656_p4}}, {p_Result_12_i_i_fu_666_p4}}, {p_Result_13_i_i_fu_676_p4}}, {p_Result_14_i_i_fu_686_p4}}, {p_Result_6_i_i_fu_616_p4}}, {p_Result_7_i_i_fu_626_p4}}, {p_Result_8_i_i_fu_636_p4}}, {p_Result_10_i_i_fu_646_p4}};

integer ap_tvar_int_1;

always @ (shl_ln414_2_fu_1094_p2) begin
    for (ap_tvar_int_1 = 512 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 511 - 0) begin
            tmp_5_fu_1100_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_5_fu_1100_p4[ap_tvar_int_1] = shl_ln414_2_fu_1094_p2[511 - ap_tvar_int_1];
        end
    end
end

assign tmp_6_i_i_fu_2598_p8 = {{{{{{{frame_ctx_remote_ip_1_fu_472_p4}, {my_ip}}, {48'd289407040}}, {trunc_ln674_4_fu_2594_p1}}, {p_Result_51_i_i_fu_2584_p4}}, {trunc_ln674_3_fu_2564_p1}}, {p_Result_49_i_i_fu_2554_p4}};

assign tmp_data_V_1_fu_431_p1 = tx_to_hdr_gen_dout[511:0];

assign tmp_i_i_nbreadreq_fu_332_p3 = tx_to_hdr_gen_empty_n;

assign tmp_immdt_V_fu_482_p4 = {{axis_frame_ctx_to_hdr_gen_dout[280:249]}};

assign tmp_last_V_fu_435_p3 = tx_to_hdr_gen_dout[32'd576];

assign tmp_opcode_V_fu_454_p4 = {{axis_frame_ctx_to_hdr_gen_dout[71:64]}};

assign tmp_payload_len_V_fu_444_p4 = {{axis_frame_ctx_to_hdr_gen_dout[63:48]}};

assign trunc_ln414_1_fu_898_p1 = select_ln215_fu_876_p3[9:0];

assign trunc_ln414_2_fu_1038_p1 = select_ln155_fu_862_p3[9:0];

assign trunc_ln414_3_fu_1042_p1 = select_ln215_fu_876_p3[9:0];

assign trunc_ln414_fu_894_p1 = select_ln155_fu_862_p3[9:0];

assign trunc_ln674_1_fu_1314_p1 = rdma_udp_port_dst[7:0];

assign trunc_ln674_2_fu_1920_p1 = udp_len_V_3_fu_1892_p2[7:0];

assign trunc_ln674_3_fu_2564_p1 = ip_len_V_fu_2548_p2[7:0];

assign trunc_ln674_4_fu_2594_p1 = id[7:0];

assign trunc_ln674_fu_518_p1 = axis_frame_ctx_to_hdr_gen_dout[7:0];

assign trunc_ln_fu_508_p4 = {{axis_frame_ctx_to_hdr_gen_dout[68:64]}};

assign tx_to_crc_and_remainder_din = dout_fu_2655_p3;

assign udp_len_V_3_fu_1892_p2 = (zext_ln691_2_fu_1888_p1 + udp_len_V_fu_1354_p2);

assign udp_len_V_fu_1354_p2 = (zext_ln691_fu_1350_p1 + tmp_payload_len_V_fu_444_p4);

assign xor_ln11_fu_1984_p2 = (ecn_for_ack_dout ^ 1'd1);

assign xor_ln414_1_fu_932_p2 = (select_ln414_fu_908_p3 ^ 10'd511);

assign xor_ln414_2_fu_992_p2 = (512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 ^ and_ln414_fu_986_p2);

assign xor_ln414_3_fu_1046_p2 = (trunc_ln414_2_fu_1038_p1 ^ 10'd511);

assign xor_ln414_4_fu_1076_p2 = (select_ln414_4_fu_1052_p3 ^ 10'd511);

assign xor_ln414_5_fu_1136_p2 = (512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095 ^ and_ln414_3_fu_1130_p2);

assign xor_ln414_fu_902_p2 = (trunc_ln414_fu_894_p1 ^ 10'd511);

assign zext_ln208_fu_2651_p1 = ip_len_V_reg_2689;

assign zext_ln215_1_fu_1028_p1 = p_Result_3_fu_1016_p5;

assign zext_ln215_fu_884_p1 = tmp_immdt_V_fu_482_p4;

assign zext_ln414_1_fu_942_p1 = select_ln414_1_fu_916_p3;

assign zext_ln414_2_fu_946_p1 = xor_ln414_1_fu_932_p2;

assign zext_ln414_3_fu_1082_p1 = select_ln414_6_fu_1068_p3;

assign zext_ln414_4_fu_1086_p1 = select_ln414_5_fu_1060_p3;

assign zext_ln414_5_fu_1090_p1 = xor_ln414_4_fu_1076_p2;

assign zext_ln414_fu_938_p1 = select_ln414_2_fu_924_p3;

assign zext_ln41_fu_612_p1 = tmp_opcode_V_fu_454_p4;

assign zext_ln691_1_fu_1878_p1 = retval_0_i_i1_i_i_fu_1360_p258;

assign zext_ln691_2_fu_1888_p1 = add_ln691_fu_1882_p2;

assign zext_ln691_3_fu_2534_p1 = retval_0_i_i_i_i_fu_2016_p258;

assign zext_ln691_4_fu_2544_p1 = add_ln691_2_fu_2538_p2;

assign zext_ln691_fu_1350_p1 = or_ln_fu_1342_p3;

always @ (posedge ap_clk) begin
    packet_len_preg[31:16] <= 16'b0000000000000000;
end

endmodule //tx_rdma_hdr_put_hdr
