-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ethHeader_fromICMP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    p_in_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    p_in_TVALID : IN STD_LOGIC;
    p_in_TREADY : OUT STD_LOGIC;
    p_in_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    p_in_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    p_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    p_out_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    p_out_TVALID : OUT STD_LOGIC;
    p_out_TREADY : IN STD_LOGIC;
    p_out_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_out_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    smac : OUT STD_LOGIC_VECTOR (47 downto 0) );
end;


architecture behav of ethHeader_fromICMP is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ethHeader_fromICMP_ethHeader_fromICMP,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=0.631000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=696,HLS_SYN_LUT=39,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal isFirst_V : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal lsmac_V : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal p_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_vld_reg_166 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal p_vld_reg_166_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_vld_fu_110_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal regslice_both_p_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_data_V_reg_170 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_keep_V_reg_176 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_strb_V_reg_181 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_last_V_reg_186 : STD_LOGIC_VECTOR (0 downto 0);
    signal isFirst_V_load_load_fu_130_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal isFirst_V_load_reg_191 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_isFirst_V_flag_0_phi_fu_102_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_isFirst_V_flag_0_reg_99 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_nbread_fu_64_p5_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_p_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal p_in_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal p_in_TVALID_int_regslice : STD_LOGIC;
    signal p_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_p_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_p_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal p_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_p_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_p_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_p_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal p_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_p_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_p_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_p_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal p_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_p_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_p_in_V_last_V_U_ack_in : STD_LOGIC;
    signal p_out_TVALID_int_regslice : STD_LOGIC;
    signal p_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_p_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_p_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_p_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_p_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_p_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_p_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_p_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_p_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_p_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_p_out_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ethHeader_fromICMP_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_p_in_V_data_V_U : component ethHeader_fromICMP_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => p_in_TDATA,
        vld_in => p_in_TVALID,
        ack_in => regslice_both_p_in_V_data_V_U_ack_in,
        data_out => p_in_TDATA_int_regslice,
        vld_out => p_in_TVALID_int_regslice,
        ack_out => p_in_TREADY_int_regslice,
        apdone_blk => regslice_both_p_in_V_data_V_U_apdone_blk);

    regslice_both_p_in_V_keep_V_U : component ethHeader_fromICMP_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => p_in_TKEEP,
        vld_in => p_in_TVALID,
        ack_in => regslice_both_p_in_V_keep_V_U_ack_in,
        data_out => p_in_TKEEP_int_regslice,
        vld_out => regslice_both_p_in_V_keep_V_U_vld_out,
        ack_out => p_in_TREADY_int_regslice,
        apdone_blk => regslice_both_p_in_V_keep_V_U_apdone_blk);

    regslice_both_p_in_V_strb_V_U : component ethHeader_fromICMP_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => p_in_TSTRB,
        vld_in => p_in_TVALID,
        ack_in => regslice_both_p_in_V_strb_V_U_ack_in,
        data_out => p_in_TSTRB_int_regslice,
        vld_out => regslice_both_p_in_V_strb_V_U_vld_out,
        ack_out => p_in_TREADY_int_regslice,
        apdone_blk => regslice_both_p_in_V_strb_V_U_apdone_blk);

    regslice_both_p_in_V_last_V_U : component ethHeader_fromICMP_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => p_in_TLAST,
        vld_in => p_in_TVALID,
        ack_in => regslice_both_p_in_V_last_V_U_ack_in,
        data_out => p_in_TLAST_int_regslice,
        vld_out => regslice_both_p_in_V_last_V_U_vld_out,
        ack_out => p_in_TREADY_int_regslice,
        apdone_blk => regslice_both_p_in_V_last_V_U_apdone_blk);

    regslice_both_p_out_V_data_V_U : component ethHeader_fromICMP_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_data_V_reg_170,
        vld_in => p_out_TVALID_int_regslice,
        ack_in => p_out_TREADY_int_regslice,
        data_out => p_out_TDATA,
        vld_out => regslice_both_p_out_V_data_V_U_vld_out,
        ack_out => p_out_TREADY,
        apdone_blk => regslice_both_p_out_V_data_V_U_apdone_blk);

    regslice_both_p_out_V_keep_V_U : component ethHeader_fromICMP_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_keep_V_reg_176,
        vld_in => p_out_TVALID_int_regslice,
        ack_in => regslice_both_p_out_V_keep_V_U_ack_in_dummy,
        data_out => p_out_TKEEP,
        vld_out => regslice_both_p_out_V_keep_V_U_vld_out,
        ack_out => p_out_TREADY,
        apdone_blk => regslice_both_p_out_V_keep_V_U_apdone_blk);

    regslice_both_p_out_V_strb_V_U : component ethHeader_fromICMP_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_strb_V_reg_181,
        vld_in => p_out_TVALID_int_regslice,
        ack_in => regslice_both_p_out_V_strb_V_U_ack_in_dummy,
        data_out => p_out_TSTRB,
        vld_out => regslice_both_p_out_V_strb_V_U_vld_out,
        ack_out => p_out_TREADY,
        apdone_blk => regslice_both_p_out_V_strb_V_U_apdone_blk);

    regslice_both_p_out_V_last_V_U : component ethHeader_fromICMP_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_V_reg_186,
        vld_in => p_out_TVALID_int_regslice,
        ack_in => regslice_both_p_out_V_last_V_U_ack_in_dummy,
        data_out => p_out_TLAST,
        vld_out => regslice_both_p_out_V_last_V_U_vld_out,
        ack_out => p_out_TREADY,
        apdone_blk => regslice_both_p_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (p_vld_fu_110_p1 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln21_fu_134_p2 = ap_const_lv1_1))) then
                isFirst_V <= p_in_TLAST_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_vld_fu_110_p1 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                isFirst_V_load_reg_191 <= isFirst_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((isFirst_V_load_reg_191 = ap_const_lv1_1) and (p_vld_reg_166 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                lsmac_V <= tmp_data_V_reg_170(95 downto 48);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_vld_reg_166 <= empty_nbread_fu_64_p5_0;
                p_vld_reg_166_pp0_iter1_reg <= p_vld_reg_166;
                tmp_data_V_reg_170 <= p_in_TDATA_int_regslice;
                tmp_keep_V_reg_176 <= p_in_TKEEP_int_regslice;
                tmp_last_V_reg_186 <= p_in_TLAST_int_regslice;
                tmp_strb_V_reg_181 <= p_in_TSTRB_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, p_vld_reg_166, ap_enable_reg_pp0_iter2, p_vld_reg_166_pp0_iter1_reg, regslice_both_p_out_V_data_V_U_apdone_blk, p_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_p_out_V_data_V_U_apdone_blk = ap_const_logic_1) or ((p_vld_reg_166_pp0_iter1_reg = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0)))) or ((p_vld_reg_166 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (p_out_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, p_vld_reg_166, ap_enable_reg_pp0_iter2, p_vld_reg_166_pp0_iter1_reg, ap_block_state2_io, regslice_both_p_out_V_data_V_U_apdone_blk, ap_block_state3_io, p_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_p_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((p_vld_reg_166_pp0_iter1_reg = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or ((p_vld_reg_166 = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, p_vld_reg_166, ap_enable_reg_pp0_iter2, p_vld_reg_166_pp0_iter1_reg, ap_block_state2_io, regslice_both_p_out_V_data_V_U_apdone_blk, ap_block_state3_io, p_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_p_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((p_vld_reg_166_pp0_iter1_reg = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or ((p_vld_reg_166 = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0)))));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_io_assign_proc : process(p_vld_reg_166, p_out_TREADY_int_regslice)
    begin
                ap_block_state2_io <= ((p_vld_reg_166 = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(p_vld_reg_166, p_out_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((p_vld_reg_166 = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(p_vld_reg_166_pp0_iter1_reg, p_out_TREADY_int_regslice)
    begin
                ap_block_state3_io <= ((p_vld_reg_166_pp0_iter1_reg = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(p_vld_reg_166_pp0_iter1_reg, regslice_both_p_out_V_data_V_U_apdone_blk, p_out_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((regslice_both_p_out_V_data_V_U_apdone_blk = ap_const_logic_1) or ((p_vld_reg_166_pp0_iter1_reg = ap_const_lv1_1) and (p_out_TREADY_int_regslice = ap_const_logic_0)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_isFirst_V_flag_0_phi_fu_102_p4_assign_proc : process(p_vld_fu_110_p1, isFirst_V_load_load_fu_130_p1, ap_phi_reg_pp0_iter0_isFirst_V_flag_0_reg_99)
    begin
        if ((p_vld_fu_110_p1 = ap_const_lv1_1)) then
            if ((isFirst_V_load_load_fu_130_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_isFirst_V_flag_0_phi_fu_102_p4 <= ap_const_lv1_0;
            elsif ((isFirst_V_load_load_fu_130_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_isFirst_V_flag_0_phi_fu_102_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_isFirst_V_flag_0_phi_fu_102_p4 <= ap_phi_reg_pp0_iter0_isFirst_V_flag_0_reg_99;
            end if;
        else 
            ap_phi_mux_isFirst_V_flag_0_phi_fu_102_p4 <= ap_phi_reg_pp0_iter0_isFirst_V_flag_0_reg_99;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_isFirst_V_flag_0_reg_99 <= "X";
    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    empty_nbread_fu_64_p5_0 <= (0=>(p_in_TVALID_int_regslice), others=>'-');
    isFirst_V_load_load_fu_130_p1 <= isFirst_V;
    or_ln21_fu_134_p2 <= (p_in_TLAST_int_regslice or ap_phi_mux_isFirst_V_flag_0_phi_fu_102_p4);
    p_in_TREADY <= regslice_both_p_in_V_data_V_U_ack_in;

    p_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, p_in_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_in_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            p_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    p_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, p_vld_reg_166, ap_enable_reg_pp0_iter2, p_vld_reg_166_pp0_iter1_reg, p_out_TREADY_int_regslice)
    begin
        if ((((p_vld_reg_166_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((p_vld_reg_166 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_out_TDATA_blk_n <= p_out_TREADY_int_regslice;
        else 
            p_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_out_TVALID <= regslice_both_p_out_V_data_V_U_vld_out;

    p_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, p_vld_reg_166, ap_block_pp0_stage0_11001)
    begin
        if (((p_vld_reg_166 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            p_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_vld_fu_110_p1 <= empty_nbread_fu_64_p5_0;
    smac <= lsmac_V;
end behav;
